### ISSUE TITLE
Can this plugin be used as standalone exe/binary, which can be run for use in vim?

### ISSUE THREAD

**Issue by asknet** [dangmai/prettier-plugin-apex#1]
Hi,
Please let me if this can be used as standalone exe/binary? It would be helpful If that is an option.
In case you might be interested (https://github.com/Chiel92/vim-autoformat#default-formatprograms)

**Comment by dangmai** [comment]
Hi @asknet, thank you for your interest in this project.

For `vim-autoformat` it looks like they already supported `prettier` as an external program to use, so I don't think we need to do anything special in this project to support it. Once I release this as a package on `npm`, you can just install it globally and `prettier` will use it for Apex classes and triggers.

Does that answer your question?
