### ISSUE TITLE
Should break after assignment instead of method arguments

### ISSUE THREAD

**Issue by jdcrensh** [dangmai/prettier-plugin-apex#102]
**Input:**

```apex
PromotionFactory.IPromotion promotionCalculator = PromotionFactory.getPromotionInstance(promo);
```

**Actual output:**

```apex
PromotionFactory.IPromotion promotionCalculator = PromotionFactory.getPromotionInstance(
  promo
);
```

**Expected output:**

```apex
PromotionFactory.IPromotion promotionCalculator =
  PromotionFactory.getPromotionInstance(promo);
```

**Comment by dangmai** [comment]
Thank you for the report! This is one of the cases that I had to make a tough decision on, and I chose to follow Prettier JS's decision, so that the output from Prettier Apex and Prettier JS (for Aura/LWC) look similar to each other.
