### ISSUE TITLE
Running local installation, can't resolve ESLint package version

### ISSUE THREAD

**Issue by deckblad** [dangmai/prettier-plugin-apex#1085]
## Describe your Issue

I'm trying to run the local install command: npm install --save-dev prettier prettier-plugin-apex

And am getting this error logfile:

While resolving: @salesforce/eslint-config-lwc@0.7.0
Found: eslint@7.32.0
node_modules/eslint
  peer eslint@">=6.0.0" from @lwc/eslint-plugin-lwc@0.10.0
  node_modules/@lwc/eslint-plugin-lwc
    @lwc/eslint-plugin-lwc@"~0.10.0" from @salesforce/eslint-config-lwc@0.7.0
    node_modules/@salesforce/eslint-config-lwc
      dev @salesforce/eslint-config-lwc@"^0.7.0" from the root project
  peer eslint@">=5.0.0" from @salesforce/eslint-plugin-aura@1.4.0
  node_modules/@salesforce/eslint-plugin-aura
    dev @salesforce/eslint-plugin-aura@"^1.4.0" from the root project
  peer eslint@"*" from @typescript-eslint/experimental-utils@2.34.0
  node_modules/@typescript-eslint/experimental-utils
    @typescript-eslint/experimental-utils@"^2.5.0" from eslint-plugin-jest@23.8.2
    node_modules/eslint-plugin-jest
      eslint-plugin-jest@"~23.8.2" from @salesforce/eslint-config-lwc@0.7.0
      node_modules/@salesforce/eslint-config-lwc
        dev @salesforce/eslint-config-lwc@"^0.7.0" from the root project
  peer eslint@">= 4.12.1" from babel-eslint@10.1.0
  node_modules/babel-eslint
    peer babel-eslint@">=10.0.0" from @lwc/eslint-plugin-lwc@0.10.0
    node_modules/@lwc/eslint-plugin-lwc
      @lwc/eslint-plugin-lwc@"~0.10.0" from @salesforce/eslint-config-lwc@0.7.0
      node_modules/@salesforce/eslint-config-lwc
        dev @salesforce/eslint-config-lwc@"^0.7.0" from the root project
    babel-eslint@"~10.1.0" from @salesforce/eslint-config-lwc@0.7.0
    node_modules/@salesforce/eslint-config-lwc
      dev @salesforce/eslint-config-lwc@"^0.7.0" from the root project
  peer eslint@">=3.14.1" from eslint-config-prettier@6.15.0
  node_modules/eslint-config-prettier
    dev eslint-config-prettier@"^6.11.0" from the root project
  peer eslint@">=5" from eslint-plugin-jest@23.8.2
  node_modules/eslint-plugin-jest
    eslint-plugin-jest@"~23.8.2" from @salesforce/eslint-config-lwc@0.7.0
    node_modules/@salesforce/eslint-config-lwc
      dev @salesforce/eslint-config-lwc@"^0.7.0" from the root project
  dev eslint@"^7.32.0" from the root project

Could not resolve dependency:
peer eslint@"^6.0.0" from @salesforce/eslint-config-lwc@0.7.0
node_modules/@salesforce/eslint-config-lwc
  dev @salesforce/eslint-config-lwc@"^0.7.0" from the root project

Conflicting peer dependency: eslint@6.8.0
node_modules/eslint
  peer eslint@"^6.0.0" from @salesforce/eslint-config-lwc@0.7.0
  node_modules/@salesforce/eslint-config-lwc
    dev @salesforce/eslint-config-lwc@"^0.7.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

**Additional information (please fill this out)**:

On windows 11 with Java 17, latest SFDX CLI, latest Node LTS.

**Comment by dangmai** [comment]
This error most likely doesn't come from this project, since the dependencies listed in your stack trace are not listed in Prettier Apex `package.json` at all. I have a feeling that your `package.json` is broken even before you install Prettier Apex.

Closing this to avoid clutter, but feel free to post the content of your `package.json` here and I'll see what I can do to help.
