### ISSUE TITLE
VSCode support

### ISSUE THREAD

**Issue by RandallFlagg** [dangmai/prettier-plugin-apex#110]
Hi,

This looks like a great project but I can't seem to see support in VSCode even though the issue stated in the README file is [resolved](https://github.com/prettier/prettier-vscode/pull/899).

Do I need to do something else?

Thanks in advance.

**Comment by dangmai** [comment]
Hi,

I don't think there has been an official release yet for the VSCode plugin with support for Prettier plugins - as can be seen here on the Releases page: https://github.com/prettier/prettier-vscode/releases Once a new version has been released I will update the README file for more up to date information.

**Comment by RandallFlagg** [comment]
@dangmai Thanks

**Comment by jefersonchaves** [comment]
Hey @dangmai - I was looking at the [Changelog](https://github.com/prettier/prettier-vscode/blob/master/CHANGELOG.md) and it seems that on next version they will allow the usage of the prettier local instance (see this [Pull Request 899](https://github.com/prettier/prettier-vscode/pull/899)).

**Comment by dangmai** [comment]
@jefersonchaves I do know it's getting added soon (thanks Salesforce VSCode team!), I'm just waiting for the official release to happen before I change anything on this project :smile:

**Comment by jefersonchaves** [comment]
Thanks @dangmai, awesome, and thanks for this plugin.
