### ISSUE TITLE
Security Alert: wait-on dependency is vulnerable

### ISSUE THREAD

**Issue by dschach** [dangmai/prettier-plugin-apex#1107]
## Self-Troubleshooting Checklist

- [x] Are you running Prettier Apex >= 2.0.0? If Yes, have you gone through the [Upgrade Guide](https://github.com/dangmai/prettier-plugin-apex/wiki/Upgrading-to-Prettier-Apex-v2)?
- [x] Are you running Java < 11? If Yes, you need to install a newer Java version.

## Describe your Issue

Alert from npm audit:
```
axios  0.8.1 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
fix available via `npm audit fix --force`
Will install prettier-plugin-apex@1.4.0, which is a breaking change
node_modules/axios
  wait-on  >=5.0.0-rc.0
  Depends on vulnerable versions of axios
  node_modules/wait-on
    prettier-plugin-apex  >=1.5.0
    Depends on vulnerable versions of wait-on
    node_modules/prettier-plugin-apex
```

**Additional information (please fill this out)**:

- OS: OS X
- Version 2.0.1
- Prettier Version 3.0.3
- Java Version 17

**Comment by dangmai** [comment]
Snyk has informed me about this for a few days already, I'm just waiting for `wait-on` to release a new version.

**Comment by dangmai** [comment]
Fixed in https://github.com/dangmai/prettier-plugin-apex/pull/1111

**Comment by jacobemerick** [comment]
Thanks @dangmai ! Could you spin up a new tag so it's easier for consumers to pull in this fix?
