### ISSUE TITLE
Running CLI checks returns false JSON issues on Apex classes

### ISSUE THREAD

**Issue by daviddawson90** [dangmai/prettier-plugin-apex#114]
I am using the CLI commands to enforce code styling in CI (GitLab CI to be precise). The agents that run the jobs are not persistent so the env needs to be setup each time.

When running the check command, I get both a failure (as it seems to check the classes as JSON files) as well as as a success that all files match the Prettier code style:

```
[error] force-app/main/default/classes/Parent.cls: SyntaxError: Unexpected token E in JSON at position 1
[error]     at JSON.parse (<anonymous>)
[error]     at Object.parse (/builds/user/example-app/node_modules/prettier-plugin-apex/src/parser.js:468:16)
[error]     at Object.parse$2 [as parse] (/builds/user/example-app/node_modules/prettier/bin-prettier.js:10631:19)
[error]     at coreFormat (/builds/user/example-app/node_modules/prettier/bin-prettier.js:13890:23)
[error]     at format (/builds/user/example-app/node_modules/prettier/bin-prettier.js:14148:73)
[error]     at formatWithCursor (/builds/user/example-app/node_modules/prettier/bin-prettier.js:14164:12)
[error]     at Object.formatWithCursor (/builds/user/example-app/node_modules/prettier/bin-prettier.js:42758:15)
[error]     at format$1 (/builds/user/example-app/node_modules/prettier/bin-prettier.js:44127:21)
[error]     at /builds/user/example-app/node_modules/prettier/bin-prettier.js:44322:16
[error]     at /builds/user/example-app/node_modules/prettier/bin-prettier.js:44262:14
[error] force-app/main/default/classes/ParentItem.cls: SyntaxError: Unexpected token E in JSON at position 1
[error]     at JSON.parse (<anonymous>)
[error]     at Object.parse (/builds/user/example-app/node_modules/prettier-plugin-apex/src/parser.js:468:16)
[error]     at Object.parse$2 [as parse] (/builds/user/example-app/node_modules/prettier/bin-prettier.js:10631:19)
[error]     at coreFormat (/builds/user/example-app/node_modules/prettier/bin-prettier.js:13890:23)
[error]     at format (/builds/user/example-app/node_modules/prettier/bin-prettier.js:14148:73)
[error]     at formatWithCursor (/builds/user/example-app/node_modules/prettier/bin-prettier.js:14164:12)
[error]     at Object.formatWithCursor (/builds/user/example-app/node_modules/prettier/bin-prettier.js:42758:15)
[error]     at format$1 (/builds/user/example-app/node_modules/prettier/bin-prettier.js:44127:21)
[error]     at /builds/user/example-app/node_modules/prettier/bin-prettier.js:44322:16
[error]     at /builds/user/example-app/node_modules/prettier/bin-prettier.js:44262:14
All matched files use Prettier code style!
```

These are the commands I am running in sequence:

```yml
script:
    - npm install
    - npx prettier --write .prettierrc --plugin=prettier-plugin-apex
    - npx prettier -c force-app/main/default/**/*.{trigger,cls} --parser apex --with-node-modules
```

And finally my package.json file within the DX project:

```json
{
  "name": "example-app",
  "version": "1.0.0",
  "description": "## Dev, Build and Test",
  "main": "index.js",
  "scripts": {
    "prettier": "prettier"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@gitlab.com/user/example-app.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://gitlab.com/user/example-app/issues"
  },
  "homepage": "https://gitlab.com/user/example-app#readme",
  "devDependencies": {
    "prettier": "^1.18.2",
    "prettier-plugin-apex": "^1.0.0-rc.6"
  }
}
```

I apoligise if I am doing something silly (I have used Prettier for a while but I have not delved into plugins much) but when I run the check command locally it does not print the JSON issue, whereas running it on the server is where the output is produced.

**Comment by dangmai** [comment]
Hi, thank you for the issue report! If it's possible could you attach the content of either `Parent.cls` or `ParentItem.cls`? If you'd rather not share it publicly, let me know and I can figure out a way for you to send it to me in private.

**Comment by daviddawson90** [comment]
Sure thing:

```java
public class Parent {
  public Date startDate;
  public Date endDate;
  public Decimal netTotal;
  public Decimal grossTotal;
  public Decimal taxTotal;
  public Decimal discountTotal;

  public List<ParentItem> items;

  public Parent() {
    applyDefaults();
  }

  private void applyDefaults() {}

  private void calculateTotals() {
    try {
      resetTotals();
      for (ParentItem item : items) {
        grossTotal = grossTotal + item.grossAmount;
        taxTotal = taxTotal + item.taxAmount;
        discountTotal = discountTotal + item.discountAmount;
      }
      netTotal = grossTotal + taxTotal - discountTotal;
    } catch (exception e) {
      // handle error
    }
  }

  private void resetTotals() {
    netTotal = 0;
    grossTotal = 0;
    taxTotal = 0;
    discountTotal = 0;
  }
}
```

```java
public class ParentItem {
  public Date startDate;
  public Date endDate;
  public Decimal netAmount;
  public Decimal grossAmount;
  public Decimal taxAmount;
  public Decimal discountAmount;

  public QuoteItem() {
    applyDefaults();
  }

  private void applyDefaults() {}
}
```

This is early days of a build but I wanted linting from the start, hence not much substance to the classes. However they do compile fine, and they also lint fine locally. But when I run the linting on the CI server it returns the error shown in the first post.

**Comment by dangmai** [comment]
So I ran Prettier on those files and they seem fine, I think there's an error in your config some where. Could you show me what's in the `.prettierrc` please? I have an example Gitlab repo at https://gitlab.com/dangmai/example-app that mirrors your set up, but without the `.prettierrc` file it's failing the second command (`npx prettier --write .prettierrc --plugin=prettier-plugin-apex`)

**Comment by daviddawson90** [comment]
Here is the `.prettierrc` file:

```json
{
  "trailingComma": "none",
  "overrides": [
    {
      "files": "**/lwc/**/*.html",
      "options": { "parser": "lwc" }
    },
    {
      "files": "*.{cmp,page,component}",
      "options": { "parser": "html" }
    },
    {
      "files": "*.{trigger,cls}",
      "options": { "parser": "apex" }
    }
  ]
}
```

When I run this locally it works fine also, like I said this issue only appears when running it on one of the CI agents.

Considering the agent begins with simply having to clone from git and having no prior config, it is difficult to reproduce the error as you most likely will have prior global installations/config installed locally which is making this difficult to reproduce. I was hoping there was something obvious I had missed in configuring the linter to work but it does not appear that way. Considering the final message is that the files matched linting, I am wondering if the linter is using the json parser or the json parser and then the apex parser. Either way I assume it is one of two issues; the former which means it is not running the lint with the correct parser or the latter which means it is parsing with the apex parser, but it is also trying to perform a lint with the json parser which causes the initial issues 🤔

**Comment by dangmai** [comment]
I figured it out, it's because the Gitlab CI environment does not have Java installed by default, which is required because this project uses the `jorje` parser from Salesforce which is built in Java. Hence why it runs fine on your computer but not on Gitlab - so you'll need to add a step in your `.gitlab-ci.yml` to install a JRE >= 8, for example like this: 

```yaml
default:
  image: node:12

before_script:
  - apt-get update -qq && apt-get install -y -qq default-jre
lint:
  script:
    - npm install
    - npx prettier --write .prettierrc --plugin=prettier-plugin-apex
    - npx prettier -c force-app/main/default/**/*.{trigger,cls} --parser apex --with-node-modules

```

That exact config works for me so I'll close this issue - let me know if you run into any other issue!

**Comment by daviddawson90** [comment]
you are a legend thank you 🙏 worked a treat.

considering that Java is required by the plugin it may be worthwhile doing a check either on load or during any errors that can be identified as being a likely candidate for Java not being installed prior to executing the linting commands?
