### ISSUE TITLE
Array notation being transformed to List

### ISSUE THREAD

**Issue by alan-morey** [dangmai/prettier-plugin-apex#115]
**Input:**

```apex
String[] a = new String[0];
Integer[] b = new Integer[]{};
```

**Actual output:**

```apex
String[] a = new List<String>(0);
Integer[] b = new List<Integer>{};
```

**Expected output:**

```apex
String[] a = new String[0];
Integer[] b = new Integer[]{};
```

**Additional information (please fill this out)**:

- OS: Ubuntu 16.04
- Version: 1.0.0-rc.6

**Comment by dangmai** [comment]
Thank you for the report! This is a conscious decision to ensure that the rule of 1 AST -> 1 output is followed, and the List syntax is more general than the Array syntax (i.e. anything that can be done with the Array syntax can also be done with the List syntax, but not vice versa) so I chose to go with it. The two syntax create the same AST so there is no difference in functionality.
