### ISSUE TITLE
Support for the new Apex null-coalescing operator (Spring '24)

### ISSUE THREAD

**Issue by pozil** [dangmai/prettier-plugin-apex#1176]
Hi @dangmai, the Spring '24 release introduces the [Apex null-coalescing operator](https://help.salesforce.com/s/articleView?id=release-notes.rn_apex_NullCoalescingOper.htm&release=248&type=5) `??`. It would be great to add support for this in your plugin.

I see that the Apex team recently updated the jorje parser so it looks like you could proceed with an update of your plugin. Let me know if not and I'll raise the issue with the team.

Once again, thanks a lot for your great tool.

**Comment by pozil** [comment]
Update from the tooling team: the new jorje JAR should be pushed near the Spring '24 release date (Feb 10-11).

**Comment by dangmai** [comment]
Awesome, thanks for letting me know about it. I'll add support for it when the new JAR is out!

**Comment by pozil** [comment]
Hi @dangmai, it looks like the product team [released the JAR last week](https://github.com/forcedotcom/salesforcedx-vscode/tree/develop/packages/salesforcedx-vscode-apex/out).

**Comment by dangmai** [comment]
Awesome! I'll most likely add support for this this weekend, thank you for the heads up!

**Comment by dangmai** [comment]
Support for the Null-Coaslescing Exression has been added and will be included in the next release. Thanks again for raising this!

**Comment by dangmai** [comment]
This has been released as part of `v2.1.0`.

**Comment by pozil** [comment]
Thank you so much!

**Comment by msouther-lisc** [comment]
I installed `v2.1.0`, but if I try to save a file that includes the null coalescing operator, it doesn't format, and I get this error message:

```
No handler found for apex.jorje.data.ast.Expr$NullCoalescingExpr. Please file a bug report.
```

**Comment by dangmai** [comment]
@msouther-lisc How are you running Prettier Apex? If you're running it via VSCode, did you try restarting VSCode yet?

**Comment by msouther-lisc** [comment]
@dangmai I hadn't restarted VS Code yet when I was getting the error. After restarting VS Code, I am no longer getting the error, but I'm not getting any formatting on Apex files whatsoever (other files, e.g. JavaScript files, still work OK). It looks like Prettier is disabled when I'm on an Apex file:

![image](https://github.com/dangmai/prettier-plugin-apex/assets/123027648/4474433a-9920-4a83-9524-4a3ceb844916)

There is probably a simple reason for this, but I'm not sure what I'm doing wrong.

**Comment by msouther-lisc** [comment]
I got it working after some trial and error. I added a new comment on [the workaround thread](https://github.com/dangmai/prettier-plugin-apex/issues/1168) so others can benefit from my experience.

**Comment by dangmai** [comment]
That means you upgraded from `1.13.0`, here is the guide to upgrade from v1 to v2: https://github.com/dangmai/prettier-plugin-apex/wiki/Upgrading-to-Prettier-Apex-v2 Generally speaking when you upgrade a major version there'll be some manual steps you need to take.

**Comment by msouther-lisc** [comment]
Yep, you nailed it. That's exactly what the issue was there. 😝 Many thanks for your support! Much admiration for the work you do.

**Comment by aminnaggar** [comment]
For anyone seeing this later the summary of what you need to do:

1. upgrade `prettier` to "^3.x"
2. upgrade `prettier-plugin-apex` to "^2.x"
3. add `"plugins": ["prettier-plugin-apex", "@prettier/plugin-xml"]` to your ".prettierrc" (prettier 3 needs this)
4. add `"prettier.configPath": "./.prettierrc"` to your ".vscode/settings.json" (even if it looks like it's pickup the right path in your vscode output logs)
5. restart vscode due to a [known bug](https://github.com/prettier/prettier-vscode/issues/3179)
