### ISSUE TITLE
SOQL query numbers lose negative value

### ISSUE THREAD

**Issue by jdrbc** [dangmai/prettier-plugin-apex#122]
```sh
# Prettier options (if any):
{
  "trailingComma": "none",
  "printWidth": 120,
  "overrides": [
    {
      "files": "**/lwc/**/*.html",
      "options": { "parser": "lwc" }
    },
    {
      "files": "*.{app,cmp,page,component}",
      "options": { "parser": "html" }
    }
  ]
}

prettier --write .\prettier-test.cls
```

**Input:**

```apex
public class MyClass {
  public static void test() {
    System.assertEquals(
      1,
      [SELECT Id FROM object__c WHERE number_field__c = -5].size()
    );
  }
}


```

**Actual output:**

```apex
public class MyClass {
  public static void test() {
    System.assertEquals(
      1,
      [SELECT Id FROM object__c WHERE number_field__c = 5].size()
    );
  }
}


```

**Expected output:**

```apex
public class MyClass {
  public static void test() {
    System.assertEquals(
      1,
      [SELECT Id FROM object__c WHERE number_field__c = -5].size()
    );
  }
}

```

**Additional information (please fill this out)**:

- OS: Windows 10
- Version: 1.0.0-rc.6

**Comment by dangmai** [comment]
That's very serious, thank you for bringing it to my attention! I will have a fix for it soon, in the mean time you can put a `// prettier-ignore` comment before the statement so that it doesn't get formatted by Prettier.

**Comment by jdrbc** [comment]
No problem! I'm interested to see what the fix is. I saw that there was a similar problem awhile ago in with decimals. Do you know why the start/end index don't seem to line up with the literal?

`    console.log src/printer.js:2041
      jdr
    console.log src/printer.js:2042
      { '@class': 'apex.jorje.data.soql.QueryLiteral$QueryNumber',
        '@id': '287',
        loc:
         { '@class': 'apex.jorje.data.IndexLocation',
           '@id': '288',
           startIndex: 800,
           endIndex: 804,
           line: 46,
           column: 26,
           startLine: 46,
           endLine: 46 },
        literal: { '@class': 'big-decimal', '$': 15 } }
    console.log src/printer.js:2041
      jdr
    console.log src/printer.js:2042
      { '@class': 'apex.jorje.data.soql.QueryLiteral$QueryNumber',
        '@id': '334',
        loc:
         { '@class': 'apex.jorje.data.IndexLocation',
           '@id': '335',
           startIndex: 924,
           endIndex: 925,
           line: 53,
           column: 27,
           startLine: 53,
           endLine: 53 },
        literal: { '@class': 'int', '$': -1 } }`

**Comment by dangmai** [comment]
Haha I was just debugging this and saw the exact same thing - unfortunately `jorje` (the Salesforce parser) is ... not very good at getting the correct indices for start/end positions, and there are a lot of workarounds I had to implement. I'll double check this and if it's indeed a Salesforce bug I'll send it their way to fix upstream.

**Comment by dangmai** [comment]
I have fixed this in `master` and it will be included in the next release. The underlying issue indeed lies with `jorje`, however I've found a workaround for this without having to ask them to fix it in upstream (which will take longer).

Thank you again for reporting this issue! It's a serious bug that I'm glad we found out before a `1.0.0` release.
