### ISSUE TITLE
Issue with new Null Coalescing Operator in Apex: No handler found for apex.jorje.data.ast.Expr$NullCoalescingExpr

### ISSUE THREAD

**Issue by packocz** [dangmai/prettier-plugin-apex#1245]
## Self-Troubleshooting Checklist

- [ ] Are you running Prettier Apex >= 2.0.0? If Yes, have you gone through the [Upgrade Guide](https://github.com/dangmai/prettier-plugin-apex/wiki/Upgrading-to-Prettier-Apex-v2)?
Started with version 2.0.1
- [ ] Are you running Java < 11? If Yes, you need to install a newer Java version.
NO

## Describe your Issue
When using new Null Coalescing Operatior in Apex error is thrown and file is not formatted:
_No handler found for apex.jorje.data.ast.Expr$NullCoalescingExpr. Please file a bug report._

This is just after I updated from 2.0.1 to 2.1.0. On previous version the error was:
_Unexpected token '?'..
Expecting ':' but was: ';'._

```sh
# Prettier options (if any):
{
	"plugins": ["prettier-plugin-apex"],
	"trailingComma": "none",
	"tabWidth": 4,
	"useTabs": true,
	"printWidth": 140,
	"singleQuote": true,
	"endOfLine": "lf",
	"overrides": [
		{
			"files": "**/lwc/**/*.html",
			"options": { "parser": "lwc" }
		},
		{
			"files": "*.{cmp,page,component}",
			"options": { "parser": "html" }
		}
	]
}

```
package.json
```
{
	"name": "sfc-pc",
	"private": true,
	"version": "1.0.0",
	"description": "ČSAS People & Customer Application",
	"scripts": {
		"lint": "eslint **/{aura,lwc}/**",
		"test": "npm run test:unit",
		"test:unit": "sfdx-lwc-jest",
		"test:unit:watch": "sfdx-lwc-jest --watch",
		"test:unit:debug": "sfdx-lwc-jest --debug",
		"test:unit:coverage": "sfdx-lwc-jest --coverage -- --passWithNoTests",
		"prettier": "prettier --write \"src/**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}\"",
		"prettier:check": "prettier --check \"src/**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}\"",
		"postinstall": "husky install",
		"precommit": "lint-staged",
		"prepare": "husky install"
	},
	"devDependencies": {
		"@babel/traverse": ">=7.23.2",
		"@lwc/eslint-plugin-lwc": "^1.1.2",
		"@prettier/plugin-xml": "^2.0.1",
		"@salesforce/eslint-config-lwc": "^3.2.3",
		"@salesforce/eslint-plugin-aura": "^2.0.0",
		"@salesforce/eslint-plugin-lightning": "^1.0.0",
		"@salesforce/sfdx-lwc-jest": "^1.4.0",
		"babel-eslint": "^10.1.0",
		"eslint": "^7.0.0",
		"eslint-config-prettier": "^6.11.0",
		"eslint-plugin-import": "^2.25.4",
		"eslint-plugin-jest": "^26.1.2",
		"husky": "^7.0.4",
		"lint-staged": "^12.3.7",
		"postcss": ">=8.4.31",
		"prettier": ">=3.1.1",
		"prettier-plugin-apex": ">=2.0.1",
		"semver": ">=7.5.2",
		"tough-cookie": ">=4.1.3",
		"word-wrap": ">=1.2.4"
	},
	"lint-staged": {
		"**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}": [
			"prettier --write"
		],
		"**/{aura,lwc}/**": [
			"eslint"
		]
	},
	"dependencies": {
		"-": "^0.0.1",
		"g": "^2.0.1"
	}
}
```

**Additional information (please fill this out)**:

- OS: [e.g. Windows/OS X/Ubuntu]
MacOs 14.2
- Version (you can check this by running `npm ls prettier-plugin-apex`): [e.g. `prettier-plugin-apex@2.0.0`]
prettier-plugin-apex@2.1.0
- Prettier Version (you can check this by running `npm ls prettier`): [e.g. `prettier@3.0.0`]
prettier@3.1.1
- Java Version (you can check this by running `java -version`): [e.g. `openjdk version "11"`]
java version "17.0.8" 2023-07-18 LTS
Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)

**Comment by dangmai** [comment]
Hi, are you running Prettier Apex on VSCode? If so, you need to restart VSCode for it to work.

**Comment by alesremta-ext43767** [comment]
> Hi, are you running Prettier Apex on VSCode? If so, you need to restart VSCode for it to work.

Thank you! It works of course. I've restarted the Extension Host a couple of times. Didn't think to restart the whole thing.

**Comment by dangmai** [comment]
Nice! Some folks have laid out the summary here: https://github.com/dangmai/prettier-plugin-apex/issues/1176#issuecomment-1960473218
