### ISSUE TITLE
Type Name not Capitalized

### ISSUE THREAD

**Issue by monirkohi2006** [dangmai/prettier-plugin-apex#127]
```sh
# Prettier options (if any):
```

**Input:**

```apex
list<Timecard_Compliance_Assessment__c> assessmentUpsertList = new list<Timecard_Compliance_Assessment__c>();
map<Id, Timecard_Compliance_Summary__c> summaryMap = new map<Id, Timecard_Compliance_Summary__c>();
```

**Actual output:**

```apex
list<Timecard_Compliance_Assessment__c> assessmentUpsertList = new List<Timecard_Compliance_Assessment__c>();
map<Id, Timecard_Compliance_Summary__c> summaryMap = new Map<Id, Timecard_Compliance_Summary__c>();
```

**Expected output:**

```apex
List<Timecard_Compliance_Assessment__c> assessmentUpsertList = new List<Timecard_Compliance_Assessment__c>();
Map<Id, Timecard_Compliance_Summary__c> summaryMap = new Map<Id, Timecard_Compliance_Summary__c>();
```

**Additional information (please fill this out)**:

- OS: Windows 10
- VS Code: Latest Version as of 09/18/2019
- Version: "prettier-plugin-apex": "^1.0.0-rc.6"

**Comment by dangmai** [comment]
Thank you for the bug report! I agree with your expected output, unfortunately the Salesforce parser does not give me enough information to make that transformation - i.e. in this statement:

`list<Timecard_Compliance_Assessment__c> assessmentUpsertList = new list<Timecard_Compliance_Assessment__c>();`

Salesforce parser tells me the second `list` is a NewListInit and I can safely capitalize the word `List`. However, the first `list` is only given as a String without any further context, so it's very risky to try and transform it.
