### ISSUE TITLE
SOQL Query Formatting configuration

### ISSUE THREAD

**Issue by steals** [dangmai/prettier-plugin-apex#129]
Is there a way to configure how the SOQL Query is formatted? Currently, when the query has a lot of fields all of them are placed on the new line.

This is my `prettierrc`
```sh
{
  "trailingComma": "none",
  "overrides": [
    {
      "files": "**/lwc/**/*.html",
      "options": { "parser": "lwc" }
    },
    {
      "files": "*.{cmp,page,component}",
      "options": { "parser": "html" }
    }
  ],
  "printWidth": 120,
  "tabWidth": 4
}
```

```apex
List records = [
    SELECT
        Field1__c, Field2__c, Field3__c, Field4__c, Field5__c, Field6__c, 
        Field7__c, Field8__c, Field9__c, Field10__c, Field11__c, Field12__c,
        Field13__c, Field14__c, Field15__c, Field16__c, Field17__c, Field18__c
    FROM MyObject__c
    WHERE Foo__c = 'Bar'
    ORDER BY Field1__c
];
```

**Actual output:**

```apex
List records = [
    SELECT
        Field1__c, 
        Field2__c, 
        Field3__c,
        Field4__c, 
        Field5__c, 
        Field6__c, 
        Field7__c,
        Field8__c, 
        Field9__c, 
        Field10__c,
        Field11__c,
        Field12__c,
        Field13__c,
        Field14__c,
        Field15__c,
        Field16__c,
        Field17__c,
        Field18__c
    FROM MyObject__c
    WHERE Foo__c = 'Bar'
    ORDER BY Field1__c
];
```

**Expected output:**

```apex
List records = [
    SELECT
        Field1__c, Field2__c, Field3__c, Field4__c, Field5__c, Field6__c, 
        Field7__c, Field8__c, Field9__c, Field10__c, Field11__c, Field12__c,
        Field13__c, Field14__c, Field15__c, Field16__c, Field17__c, Field18__c
    FROM MyObject__c
    WHERE Foo__c = 'Bar'
    ORDER BY Field1__c
];
```

**Additional information (please fill this out)**:

- Version: 1.0.0-rc.6

**Comment by dangmai** [comment]
Thank you for the report. There is currently no configuration for SOQL formatting, and I don't foresee adding any in the future. This library is meant to be very opinionated, and IMO the current formatting decision makes sense for a lot of people - when you add new fields to the query in the middle of the list, in your expected output all the lines that come after it will be affected and lead to unexpected diffs in the source control system, vs the current formatting where the added lines are the only ones that are different.

**Comment by steals** [comment]
Can you consider an option to add a global flag to disable SOQL formatting at all? 
In the enterprise-scale projects, it's a very common situation when the SOQL query has 50+ fields and scrolling those lines is not a good experience.

Also if you check official doc you will never see the queries formatted with each filed on a new line
https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_examples.htm
https://trailhead.salesforce.com/en/content/learn/modules/apex_database/apex_database_soql

**Comment by dangmai** [comment]
I'm sympathetic to your reasoning, I work in a large enterprise and I know the pain of maintaining a large query. Nevertheless I'm not planning to add a flag to disable SOQL or SOSL formatting, that would add maintenance cost to this project that I'd rather not take on. One thing you might want to do is let Prettier handle most of the SOQL queries that are small, then for the bigger ones you can add a `// prettier-ignore` before the statement, and it won't get formatted.
