### ISSUE TITLE
Dangling comments are not printed

### ISSUE THREAD

**Issue by dangmai** [dangmai/prettier-plugin-apex#13]
For example:
```
class Comments {
  // Dangling Comment
}
```
will be turned to:
```
class Comments {}
```

**Comment by dangmai** [comment]
Partially fixed in https://github.com/dangmai/prettier-plugin-apex/commit/5ab40b69f6474b57607378f16ecbf2867a560fbb

The only exception (that I'm aware of) is in a Trigger Declaration. Somehow `jorje` decides that a Trigger Declaration starts and ends with the word `trigger`, which is messing up the algorithm that attaches comments to nodes.

**Comment by dangmai** [comment]
@ntotten @vazexqi

I think I need help from a Salesforce dev here for this issue. The problem is when parsing an empty trigger, `jorje` does not give me the correct `startIndex` and `endIndex` of the trigger node. For example:

```
trigger myAccountTrigger on Account(after insert) {
  // Inline Comments

  /* Block Comments */
}
```
`jorje` gives the following location for the `TriggerDeclUnit`:

```
startIndex = 0
endIndex = 7
line = 1
column = 1
```
Which is not enough information for me to attach comments to the correct nodes in the AST (other declarations like `ClassDecl` or `InterfaceDecl` do not have this issue). I can't think of a way to handle this, except for changing the behavior of `jorje` somehow, which is why I'm reaching out to you guys.

Thanks in advance!

**Comment by vazexqi** [comment]
>The only exception (that I'm aware of) is in a Trigger Declaration. Somehow jorje decides that a Trigger Declaration starts and ends with the word trigger, which is messing up the algorithm that attaches comments to nodes.

@dangmai - OK. I will ping the team about this and have them take a look. Does this only happen on triggers? Does it work as you expect on classes that you have tested on?

**Comment by dangmai** [comment]
@vazexqi thank you Nick, I really appreciate it! No other declaration types have this problem as far as I'm aware. `ClassDecl`, `InterfaceDecl`, `EnumDecl` and `BlockStmnt` are the main ones that I use to attach dangling comments, and they all report the correct start and end indices for their entire blocks.

**Comment by praksb** [comment]
@dangmai I just release a fix for this issue. Checkout: https://github.com/forcedotcom/salesforcedx-vscode/commit/b8e6d2f99f42b11b4d8c27140f22837a19c25690

**Comment by dangmai** [comment]
Awesome, thanks @praksb! I'll update the bundled jorje version to include the fix!
