### ISSUE TITLE
[BUG] Node.js Windows breaking change causes: Error: spawn EINVAL

### ISSUE THREAD

**Issue by nwcm** [dangmai/prettier-plugin-apex#1347]
## Self-Troubleshooting Checklist

- [x] Are you running Prettier Apex >= 2.0.0? If Yes, have you gone through the [Upgrade Guide](https://github.com/dangmai/prettier-plugin-apex/wiki/Upgrading-to-Prettier-Apex-v2)?
- [ ] Are you running Java < 11? If Yes, you need to install a newer Java version.

## Describe your Issue

Node have seemingly including a breaking change into a security patch `v18.20.2`, `v20.12.2`, `v21.7.3`. This patch covered in https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2

This plugin fails on any Apex files when using these versions of node.js. 

This line is the issue, where use of spawn cannot accept `.bat` or `.exe` anymore. https://github.com/dangmai/prettier-plugin-apex/blob/0bf44b72197acabdb48fc567c80687f5bbf12f27/packages/prettier-plugin-apex/src/parser.ts#L36

More discussion here https://github.com/nodejs/node/issues/52554

```log
force-app/main/utilities/classes/t.cls
[error] force-app/main/utilities/classes/t.cls: Error: spawn EINVAL
[error]     at ChildProcess.spawn (node:internal/child_process:421:11)
[error]     at Object.spawn (node:child_process:761:9)
[error]     at file:///C:/Users/xx/repos/bb/node_modules/prettier-plugin-apex/dist/src/parser.js:12:38
[error]     at new Promise (<anonymous>)
[error]     at parseTextWithSpawn (file:///C:/Users/xx/repos/bb/node_modules/prettier-plugin-apex/dist/src/parser.js:11:12)
[error]     at Object.parse (file:///C:/Users/xx/repos/bb/node_modules/prettier-plugin-apex/dist/src/parser.js:446:31)
[error]     at parse4 (file:///C:/Users/xx/repos/bb/node_modules/prettier/index.mjs:22117:24)
[error]     at async coreFormat (file:///C:/Users/xx/repos/bb/node_modules/prettier/index.mjs:22607:7)
[error]     at async formatWithCursor (file:///C:/Users/xx/repos/bb/node_modules/prettier/index.mjs:22809:14)
[error]     at async formatFiles (file:///C:/Users/xx/repos/bb/node_modules/prettier/internal/cli.mjs:6673:18)
```

**Additional information (please fill this out)**:

- OS: [e.g. Windows]
- Version`2.1.1`
- Prettier Version `3.2.4`
- Java Version `openjdk 17.0.10 2024-01-16`

**Comment by dangmai** [comment]
Wow, that's such a big change coming in a patch version for NodeJS. Thank you so much for bringing it up to my attention! 😇

**Comment by dangmai** [comment]
I've release `v2.1.2` with your fix. Thanks again for your contribution!
