### ISSUE TITLE
Unexpected a break line for a field value set up code

### ISSUE THREAD

**Issue by jairzh** [dangmai/prettier-plugin-apex#136]
```sh
# Prettier options (if any):
```

**Input:**

```apex
// code snippet
Account account = new Account(
    Id = testAcount.Id,
    Body__c = JSON.serialize(
        new Map<String, Object>{'Content' => 'Hello'}
     ),
    Name = 'acme'
);
```

**Actual output:**

```apex
// code snippet
Account account = new Account(
    Id = testAcount.Id,
    Body__c = 
        JSON.serialize(
            new Map<String, Object>{'Content' => 'Hello'}
        ),
    Name = 'acme'
);
```

**Expected output:**

```apex
// code snippet
Account account = new Account(
    Id = testAcount.Id,
    Body__c = JSON.serialize(
        new Map<String, Object>{'Content' => 'Hello'}
    ),
    Name = 'acme'
);
```

**Additional information (please fill this out)**:

- OS: [e.g. Windows/OS X/Ubuntu]
- Version: [e.g. 1.0.0]

**Comment by dangmai** [comment]
Thank you for the report! I agree with your expected output, although changing the formatting to that might not be trivial. I'll see what I can do.

**Comment by jairzh** [comment]
Thanks your response. By the way, the `v1.0.0-rc.5` can format the code as the expected output.

**Comment by dangmai** [comment]
This has been fixed in `master` and will be included in the next release. It took a while because fixing it requires finding a different way to fix a separate issue (that was initially fixed in rc.5 as you noted). Hopefully I didn't introduce any regressions by handling it in the new way.

Thanks again for the bug report!
