### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'unit'). Prettier 3.2.5. Prettier-plugin-apex 2.1.3.

### ISSUE THREAD

**Issue by constantine-prokopenko-vrp** [dangmai/prettier-plugin-apex#1361]
## I cannot format the code using CLI or in VS Code.
Each time I'm getting an exception. Below you can find the error message.

```
TypeError: Cannot read properties of undefined (reading 'unit')
    at AstPath.call (file:///d:/Work/TestProject/MyApp/test/test-prettier/node_modules/prettier/index.mjs:20749:20)
    at genericPrint (file:///d:/Work/TestProject/MyApp/test/test-prettier/node_modules/prettier-plugin-apex/dist/src/printer.js:2691:24)
    at Object.printGenerically [as print] (file:///d:/Work/TestProject/MyApp/test/test-prettier/node_modules/prettier-plugin-apex/dist/src/printer.js:2721:17)
    at callPluginPrintFunction (file:///d:/Work/TestProject/MyApp/test/test-prettier/node_modules/prettier/index.mjs:22303:20)
    at printAstToDoc (file:///d:/Work/TestProject/MyApp/test/test-prettier/node_modules/prettier/index.mjs:22258:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async coreFormat (file:///d:/Work/TestProject/MyApp/test/test-prettier/node_modules/prettier/index.mjs:22611:14)
    at async formatWithCursor (file:///d:/Work/TestProject/MyApp/test/test-prettier/node_modules/prettier/index.mjs:22809:14)
    at async Module.format2 (file:///d:/Work/TestProject/MyApp/test/test-prettier/node_modules/prettier/index.mjs:24194:25)
```

```sh
{
    "plugins": [
        "prettier-plugin-apex"
    ],
    "trailingComma": "none",
    "arrowParens": "always",
    "printWidth": 100,
    "singleQuote": true,
    "useTabs": false,
    "tabWidth": 4,
    "overrides": [
        {
            "files": "**/lwc/**/*.html",
            "options": {
                "parser": "lwc"
            }
        },
        {
            "files": "*.{cmp,page,component}",
            "options": {
                "parser": "html"
            }
        },
        {
            "files": "*.{trigger,cls}",
            "options": {
                "parser": "apex"
            }
        },
        {
            "files": "*.{apex}",
            "options": {
                "parser": "apex-anonymous"
            }
        }
    ]
}
```

**Additional information (please fill this out)**:

- OS: Windows 10
- Version: 2.1.3
- Prettier Version: 3.2.5
- Java Version: java version [17.0.11](https://aka.ms/download-jdk/microsoft-jdk-17.0.11-windows-x64.msi) 2024-04-16 LTS

**Comment by dangmai** [comment]
Hi, thank you for raising this. I can reproduce this now, once I figure out the root cause I'll most likely release a patch today.

**Comment by dangmai** [comment]
Hmm actually in my case it's because of a weird character in the path to my project, do you mind sharing the path to your project as well? I want to see if that's the root cause.

Also, what's the command that you used to run Prettier Apex in the command line?

**Comment by constantine-prokopenko-vrp** [comment]
`D:/Work/TestProject/MyApp/test/test-prettier`
Regarding the command, I used the context command to format the code in VS Code, and also I tried to run it using CLI `prettier --write '**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}'`. This command added to package .json file. I started it using NPM Scripts in VS Code. Then I started it using this command `npx prettier --write '**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}'` Results are the same.

**Comment by dangmai** [comment]
Could you paste the output of this command here?

```bash
npx envinfo --system --npmPackages 'prettier*' --binaries --npmGlobalPackages 'prettier*' --languages
```

Also, does this command work? It should print out `Format not specified or not supported`.

```bash
node_modules\prettier-plugin-apex\vendor\apex-ast-serializer\bin\apex-ast-serializer.bat
```

It would help me a lot in figuring out what's going on. Thank you!

**Comment by DevBPratap** [comment]
The same issue I am facing when formatting apex classes in vs code. Prettier is working with html and js file perfectly but causing a problem when formatting apex classes.
This is the error code I am seeing in the output tab

["ERROR" - 6:08:15 PM] Error formatting document.
["ERROR" - 6:08:15 PM] Cannot read properties of undefined (reading 'unit')
TypeError: Cannot read properties of undefined (reading 'unit')

**Comment by DevBPratap** [comment]
when i run the below command 
npx envinfo --system --npmPackages 'prettier*' --binaries --npmGlobalPackages 'prettier*' --languages
the result is like 

System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 2.17 GB / 7.88 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Java: 17.0.11
  npmPackages:
    prettier: 3.2.5 => 3.2.5
    prettier-plugin-apex: 2.1.3 => 2.1.3
  npmGlobalPackages:
    prettier-plugin-apex: 2.1.3
    prettier: 3.2.5
    
   and the second command  node_modules\prettier-plugin-apex\vendor\apex-ast-serializer\bin\apex-ast-serializer.bat
   when I executed the result be like
   
   Format not specified or not supported.
   What could be the cause of seeing this error? It will be extremely helpful to rectify the problem.

**Comment by dangmai** [comment]
Thank you for the info, in your project directory could you run this and paste the output here?

```bash
node -e "var p=require('child_process').spawn('node_modules\\prettier-plugin-apex\\vendor\\apex-ast-serializer\\bin\\apex-ast-serializer.bat', ['-f', 'json', '-i', '-a'], {shell: true, stdio: ['pipe','inherit','inherit']});p.stdin.write('System.debug();');p.stdin.end();"
```

**Comment by DevBPratap** [comment]
Hi @dangmai, Thank you for your reply on my thread here.
I have run the above command in my project directory, the output is in the JSON format I am mentioning here

{"apex.jorje.semantic.compiler.parser.ParserOutput": {"@id": "1","internalErrors": [],"parseErrors": [],"unit": {"@class": "apex.jorje.data.ast.CompilationUnit$AnonymousBlockUnit","@id": "3","members": [{"@class": "apex.jorje.data.ast.BlockMember$StmntBlockMember","@id": "5","stmnt": {"@class": "apex.jorje.data.ast.Stmnt$ExpressionStmnt","@id": "6","loc": {"@class": "apex.jorje.data.IndexLocation","@id": "7","startIndex": 7,"endIndex": 15,"line": 1,"column": 8},"expr": {"@class": "apex.jorje.data.ast.Expr$MethodCallExpr","@id": "8","dottedExpr": {"@id": "9"},"isSafeNav": false,"names": [{"@class": "apex.jorje.data.Identifiers$LocationIdentifier","@id": "11","loc": {"@class": "apex.jorje.data.IndexLocation","@id": "12","startIndex": 0,"endIndex": 6,"line": 1,"column": 1},"value": "System"},{"@class": "apex.jorje.data.Identifiers$LocationIdentifier","@id": "13","loc": {"@class": "apex.jorje.data.IndexLocation","@id": "14","startIndex": 7,"endIndex": 12,"line": 1,"column": 8},"value": "debug"}],"inputParameters": []}}}]},"hiddenTokenMap": []}}

Kindly review it and let me know what I can do to help with that.

**Comment by dangmai** [comment]
Do you guys mind trying upgrading to version `2.1.4` and try it again? (if you're running VSCode make sure to restart it after the upgrade).

**Comment by constantine-prokopenko-vrp** [comment]
Hello
This update resolved the issue for me.
