### ISSUE TITLE
Question on spaces introduced by Prettier

### ISSUE THREAD

**Issue by sameerseekala1** [dangmai/prettier-plugin-apex#1364]
Hi @dangmai ,

We recently started using this plugin and noticed that after formatting it is introducing more spaces where we don't need, like after if ( , for (, before and after =, ==, !=, putting each line of code into the next line. What I have observed is all spaces gets counted against the character limit. We surely need spaces at certain places like &&, ||, or after commas, but the extra spaces it is introducing at other places might result into us running into the apex char limit. Since number of lines in the code are increased (due to space or putting into new line) it is also impacting the test code coverage.

Is there any work around for this or can we configure the spaces selectively? Please let me know your thoughts on this.

Thanks,
Sameer

**Comment by dangmai** [comment]
Hello,

To be honest the number of characters used to be one of my guidelines when coming up with formatting decision, but at some point it became clear that trying to fit that in while trying to make sane and maintainable formatting decision is not something I can do in the long term. I do understand where you're coming from, and in certain cases, the number of character can be a decisive factor if I had to choose between two formatting decisions, but those cases are few and far between. I also don't see this changing anytime soon.

In your particular case, if you really want to reduce the number of newlines in the formatted code, you can try increasing the [printWidth](https://github.com/dangmai/prettier-plugin-apex?tab=readme-ov-file#configuration) configuration to something larger, which will fit more content into a single line.

Thanks for using my library, I hope you understand my POV 😁

**Comment by sameerseekala1** [comment]
@dangmai Thanks for your response. 
Any suggestion on how to deal with unwanted spaces (like after if ( , for (, before and after =, ==, !=)?
