### ISSUE TITLE
`npx install-apex-executables` takes +30 seconds

### ISSUE THREAD

**Issue by mnunezdm** [dangmai/prettier-plugin-apex#1368]
### Self-Troubleshooting Checklist

- [X] Are you running Prettier Apex >= 2.0.0? If Yes, have you gone through the [Upgrade Guide](https://github.com/dangmai/prettier-plugin-apex/wiki/Upgrading-to-Prettier-Apex-v2)?
- [X] Are you running Java >= 11? If No, you need to install a newer Java version.
- [X] Are you running VSCode and recently upgraded Prettier or Prettier Apex? If Yes, have you restarted VSCode after the upgrade?

### Describe your issue

Its strange but `npx install-apex-executables` seems to hang until timeout after correctly downloading the binary file

The `File downloaded successfully to ...` appears almost instantly but the process does not return end until after 30 seconds

If after the message is printed I manually cancel the command prettier seems to be working fine

### Prettier options (if any)

```shell
n/a
```

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 61.19 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    bun: 1.1.4 - ~/.bun/bin/bun
  Languages:
    Bash: 5.2.26 - /opt/homebrew/bin/bash
    Java: 21.0.2 - /usr/bin/javac
    Perl: 5.34.1 - /usr/bin/perl
    Python3: 3.11.7 - /opt/homebrew/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  npmPackages:
    prettier: 3.0.3 => 3.0.3 
    prettier-plugin-apex: 2.1.1 => 2.1.1
```

**Comment by dangmai** [comment]
Thanks for raising this issue, I've fixed this in `master` and it will be included in the next release.
