### ISSUE TITLE
Prettier fails when trying to format Apex using the ?. or ?? operators

### ISSUE THREAD

**Issue by naveen1883** [dangmai/prettier-plugin-apex#1379]
'Prettier' code formatter for Apex does not currently support ?. or ?? operators, so it will not format Apex using those operators. To bypass this, you can replace those operators and then try formatting. After formatting, you can undo-replace those operators (don't use Control + Z since it will undo the code formatting done by 'Prettier').

Sample VS Code find-replace expressions:

replace ?.
from: ?.
todo: /*?.*/.

undo replace ?.
from: /*?.*/.
todo: ?.

replace ??
from: ??
todo: /*??*/ ==

undo replace ??
from: /*??*/ ==
todo: ??

**Comment by dangmai** [comment]
Hi, I'm not sure why you think Prettier Apex doesn't support these operators? 
Here's an example of them working fine: https://apex.dangmai.net/#N4Ig9gDgLglmB2BnEAuUEwCcqoCy4GYAaEACzERxRAEMIBTADwFobKA6BTe+AE3szsAxmAC2IEhExgoYEQBtUZKFAjJJNTIgFK6TCSCkx4UAOoxeUUqgAcABhJQaAI3OXrKAEwkArtoAqLsgoAGY08tokeowAkkgCUABixuEAcvQA7vLG9KhQmD70AL4kIvxKQvJsiAAEABL08vJgpljyvDXAADrwNTUAbmAWNaSNzQAUAJSdPX19cVD0AOYCNTQ1ALw1+YU1APx7NWER9ADcs3MLy6vOm2t77LIAyvnGS1PnvTVFPUUgRUA

Please make sure you're running the latest version of Prettier Apex.

**Comment by naveen1883** [comment]
Hey @dangmai, thank you for replying. I thought Prettier didn't support ?? and ?. since that is what the error message was saying when I tried formatting using the 2.0.1 version. I have updated to the latest version (2.1.4) and tried formatting the same file which uses these operators and now I am getting a different error.

["ERROR" - 3:46:39 PM] Error formatting document.
["ERROR" - 3:46:39 PM] No handler found for apex.jorje.data.ast.Expr$NullCoalescingExpr. Please file a bug report.
Error: No handler found for apex.jorje.data.ast.Expr$NullCoalescingExpr. Please file a bug report.

**Comment by dangmai** [comment]
Hello, please restart VSCode, it should work afterwards.

**Comment by naveen1883** [comment]
Thank you very much! That fixed it. Also just read https://github.com/dangmai/prettier-plugin-apex/issues/1176 which explained the same thing. Should've done that before opening an issue. Thank you once again!
