### ISSUE TITLE
LWC: `<hr />` formatting causes error

### ISSUE THREAD

**Issue by getnextuser** [dangmai/prettier-plugin-apex#139]
```sh
# Prettier options (if any):
{
  "trailingComma": "none",
  "overrides": [
    {
      "files": "**/lwc/**/*.html",
      "options": { "parser": "lwc" }
    },
    {
      "files": "*.{cmp,page,component}",
      "options": { "parser": "html" }
    }
  ]
}

```

**Input:**

```html
<hr>
```

**Actual output:**

```html
<hr />
```

**Expected output:**

```html
<hr>
```

**Additional information (please fill this out)**:

- OS: Windows 10
- Version: 6.9.0

This is an important one, although it does seem semantic, because Salesforce does not allow the element of `<hr />` to be uploaded as it generates this error:

```
LWC1058: Invalid HTML syntax: non-void-html-element-start-tag-with-trailing-solidus. For more information, please visit https://html.spec.whatwg.org/multipage/parsing.html#parse-error-non-void-html-element-start-tag-with-trailing-solidus
```

Saying that `<br />` it is perfectly fine with apparently.

**Comment by dangmai** [comment]
Hi, this is not an issue from `pretter-plugin-apex`, in fact from your config you're not using this library at all. That's the behavior from Prettier itself, please open a bug report at https://github.com/prettier/prettier instead.
