### ISSUE TITLE
Getting syntax error: unexpected token while running prettier on a simple apex class

### ISSUE THREAD

**Issue by hvg2416** [dangmai/prettier-plugin-apex#1513]
### Self-Troubleshooting Checklist

- [X] Are you running Prettier Apex >= 2.0.0? If Yes, have you gone through the [Upgrade Guide](https://github.com/dangmai/prettier-plugin-apex/wiki/Upgrading-to-Prettier-Apex-v2)?
- [X] Are you running Java >= 11? If No, you need to install a newer Java version.
- [X] Are you running VSCode and recently upgraded Prettier or Prettier Apex? If Yes, have you restarted VSCode after the upgrade?

### Describe your issue

I've a basic class named `Parent.cls` which looks like below:
```
public class Parent {
  public Date startDate;
  public Date endDate;
  public Decimal netTotal;
  public Decimal grossTotal;
  public Decimal taxTotal;
  public Decimal discountTotal;

  public Parent() {
    applyDefaults();
  }

  private void applyDefaults() {}

  private void calculateTotals() {
    try {
      resetTotals();
      for (ParentItem item : items) {
        grossTotal = grossTotal + item.grossAmount;
        taxTotal = taxTotal + item.taxAmount;
        discountTotal = discountTotal + item.discountAmount;
      }
      netTotal = grossTotal + taxTotal - discountTotal;
    } catch (exception e) {
      // handle error
    }
  }

  private void resetTotals() {
    netTotal = 0;
    grossTotal = 0;
    taxTotal = 0;
    discountTotal = 0;
  }
}
```

When I run the prettier command `npm run prettier -- --write "**/*/Parent.cls" --plugin=prettier-plugin-apex`, it fails with the below error:

![cli_snapshot](https://github.com/user-attachments/assets/2fadf6ce-8fee-4b3c-9949-2c303a7abd46)

> PS: This issue is similar to https://github.com/dangmai/prettier-plugin-apex/issues/114 but the suggestions over there didn't resolve my problem.

### Prettier options (if any)

```shell
prettier: ^3.3.3
prettier-plugin-apex: ^2.1.4
```

### System Info

```shell
 System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 10.85 GB / 31.20 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Java: 21.0.2
    Python: 3.10.11
    Python3: 3.10.11
  npmPackages:
    prettier: ^3.3.3 => 3.3.3
    prettier-plugin-apex: ^2.1.4 => 2.1.4
```

**Comment by dangmai** [comment]
Hi there, the snippet you pasted in is not valid Apex, it looks like you didn't copy the whole file? Try pasting it in https://apex.dangmai.net and see if it works there as well

**Comment by hvg2416** [comment]
Hi @dangmai Thanks for responding. Sorry I messed up with the markdown. I corrected it and now you can see the `Parent` class properly. Please suggest me further to fix my issue.

PS: I also copy pasted my class on the website you mentioned and it seems it's showing the output.

**Comment by dangmai** [comment]
Could you run this command in your project and paste the output here?

```
node -e "var p=require('child_process').spawn('node_modules\\prettier-plugin-apex\\vendor\\apex-ast-serializer\\bin\\apex-ast-serializer.bat', ['-f', 'json', '-i', '-a'], {shell: true, stdio: ['pipe','inherit','inherit']});p.stdin.write('System.debug();');p.stdin.end();"
```

My guess is that you have multiple Java versions installed, but it's just a guess.

**Comment by hvg2416** [comment]
@dangmai  please have a look at the asked:

![image](https://github.com/user-attachments/assets/d3bd090e-05a0-4c0f-a75b-636a51323cb8)

PS: Yes, I do have multiple java versions' directories on my system but JAVA_HOME variable is set to the java 21 in this case as well as the correct path to the java 21's executable is added to the PATH.

**Comment by dangmai** [comment]
That's very interesting, I believe this is because you have set a `DEBUG` environment variable on your system, which makes the executable file output more verbose logging and thus no longer valid JSON.

I will find a way to fix it for the next release, but in the mean time could you temporarily remove that environment variable to see if that helps? If you can't find where it's set, you could run this:

```powershell
$env:DEBUG = ""
```

**Comment by dangmai** [comment]
This issue is closed because I made a commit referencing it - please feel free to re-open it if my workaround doesn't work for you.

**Comment by hvg2416** [comment]
Thanks @dangmai! It did solved my issue. Looking forward to the fix in next release.

PS: Also, thanks for this wonderful package of yours, it truly helps many out there.
