### ISSUE TITLE
There is no formatter for 'apex-anon' files installed.

### ISSUE THREAD

**Issue by Stragis** [dangmai/prettier-plugin-apex#155]
When language mode is set to apex-anon and I try to format document
I am getting "There is no formatter for 'apex-anon' files installed."
I have followed the guide and have prettier working properly for .apex files in language mode apex. However, apex anon code throws an error 

Anon code sample

>  for(Integer i=0; i<1; i++){
>     Account a = new Account();
>     a.Name = 'TEST - UAT Account' + i;
>     a.DBA__c = 'TEST - UAT Account' + i;
> insert a;

Error:

> ["ERROR" - 9:53:01 AM] Error formatting document.
> Error: Unexpected token 'for'.. Syntax(error = UnexpectedToken(loc = (1, 1, 0, 3), token = 'for'))
> 	at Object.parse (c:\Users\<user>\SFDX VSTS\ENHC0011121-Training-Groups\node_modules\prettier-plugin-apex\src\parser.js:504:13)
> 	at Object.parse (c:\Users\<user>\SFDX VSTS\ENHC0011121-Training-Groups\node_modules\prettier\index.js:9739:19)
> 	at coreFormat (c:\Users\<user>\SFDX VSTS\ENHC0011121-Training-Groups\node_modules\prettier\index.js:13252:23)
> 	at format (c:\Users\<user>\SFDX VSTS\ENHC0011121-Training-Groups\node_modules\prettier\index.js:13510:73)
> 	at formatWithCursor (c:\Users\<user>\SFDX VSTS\ENHC0011121-Training-Groups\node_modules\prettier\index.js:13526:12)
> 	at c:\Users\<user>\SFDX VSTS\ENHC0011121-Training-Groups\node_modules\prettier\index.js:44207:15
> 	at Object.format (c:\Users\<user>\SFDX VSTS\ENHC0011121-Training-Groups\node_modules\prettier\index.js:44226:12)
> 	at c:\Users\<user>\.vscode\extensions\esbenp.prettier-vscode-3.17.0\dist\extension.js:1:353617
> 	at t.default.safeExecution (c:\Users\<user>\.vscode\extensions\esbenp.prettier-vscode-3.17.0\dist\extension.js:1:353917)
> 	at t.default.<anonymous> (c:\Users\<user>\.vscode\extensions\esbenp.prettier-vscode-3.17.0\dist\extension.js:1:353597)
> 	at Generator.next (<anonymous>)
> 	at s (c:\Users\<user>\.vscode\extensions\esbenp.prettier-vscode-3.17.0\dist\extension.js:1:347702)
> ["INFO" - 9:53:01 AM] Formatting completed in 879.733091ms.

**Comment by dangmai** [comment]
Hi, the parser is named `apex-anonymous`, not `apex-anon`. If you try that and it still doesn't work, feel free to reopen this issue.
