### ISSUE TITLE
Support multi-line conditional statements

### ISSUE THREAD

**Issue by arvindkgs** [dangmai/prettier-plugin-apex#16]
Prettier supports multi-line statements - [Multi-line-objects](https://prettier.io/docs/en/rationale.html#multi-line-objects). However, the prettier-apex does not support the following -
if (!SObjectType.Attribute__c.fields.Name.isAccessible() || !SObjectType.Attribute__c.fields.Display_on_Actions_Tab__c.isAccessible() || !SObjectType.Attribute__c.fields.Display_Order__c.isAccessible() || !SObjectType.Attribute__c.fields.Icon__c.isAccessible() || !SObjectType.Action__c.fields.Name.isAccessible() || !SObjectType.Action__c.fields.Description__c.isAccessible() || !SObjectType.Action__c.fields.Translation_Index__c.isAccessible() || !SObjectType.Action__c.fields.State__c.isAccessible() || !SObjectType.Action__c.fields.Display_Tab__c.isAccessible() || !SObjectType.Action__c.fields.Display_Tile__c.isAccessible() || !SObjectType.Action__c.fields.Action_Type_Attribute__c.isAccessible() || !SObjectType.Action__c.fields.Tile_Type_Attribute__c.isAccessible() || !SObjectType.Action__c.fields.From_Date__c.isAccessible() || !SObjectType.Action__c.fields.To_Date__c.isAccessible() || !SObjectType.Action__c.fields.Parent__c.isAccessible() || !SObjectType.Action__c.fields.RecordTypeId.isAccessible())

It makes the above condition into a single line.

**Comment by dangmai** [comment]
Thank you for the bug report! This is indeed an issue that should get fixed.

**Comment by dangmai** [comment]
FYI I published version `1.0.0-alpha.6` that should fix this issue. Please update your local version and let me know if that's what you expected.

Thanks for the bug report again!
