### ISSUE TITLE
Spaces missing from curly braces

### ISSUE THREAD

**Issue by jwalke** [dangmai/prettier-plugin-apex#160]
```sh
# Prettier options (if any):
{
    "trailingComma": "none",
    "singleQuote": true,
    "tabWidth": 4,
    "overrides": [
        {
            "files": "**/lwc/**/*.html",
            "options": { "parser": "lwc" }
        },
        {
            "files": "*.{cmp,page,component}",
            "options": { "parser": "html" }
        }
    ]
}
```

**Input:**

```apex
            List<Contact> cs = new List<Contact>{iwContact};
```

**Actual output:**

```apex
            List<Contact> cs = new List<Contact>{iwContact};
```

**Expected output:**

```apex
            List<Contact> cs = new List<Contact>{ iwContact };
```

**Additional information (please fill this out)**:

- OS: macOS 10.14.6
- Version: 1.1.0

When I run Prettier on my Mac, spaces are not being added to braces. According to [this closed issue](https://github.com/dangmai/prettier-plugin-apex/issues/99), my understanding is that they should be added. 

When I run Prettier inside of a Docker container (same version of Prettier & Apex Prettier plugin, and same Prettier config file) spaces are added (identical to the expected output above).

**Comment by dangmai** [comment]
Hi, thank you for the bug report! Your expected output is what I expect as well, so there's definitely something weird going on here.

As a sanity check, could you run this in your Mac project dir?

```
npm ls | grep prettier-plugin-apex
```

I want to make sure that you're on `1.1.0` before diving too deep into this.

**Comment by jwalke** [comment]
That was the issue! Looks like I had `1.1.0` installed locally but had a global install of an older version of the plugin. After updating the global install this is working as expected. Thank you!

**Comment by dangmai** [comment]
No problem, glad you found the issue! :fireworks:
