### ISSUE TITLE
How to add a new line between the class name and first method

### ISSUE THREAD

**Issue by SalesforceBobLightning** [dangmai/prettier-plugin-apex#162]
it would be great if prettier did not remove the new line between the class name and the first method, for the sake of readability.

**Input:**

```apex
public class myClass {

    public void myMethod() { }
}
```

**Actual output:**

```apex
public class myClass {
    public void myMethod() { }
}
```

**Expected output:**

```apex
public class myClass {

    public void myMethod() { }
}
```

**Comment by dangmai** [comment]
Hi, thanks for using my library!

There's currently no way to add that new line in, and I don't foresee adding it in the future. This is meant to be a very opinionated formatter, and I don't quite see a huge improvement in readability in the expected output to justify supporting it.
