### ISSUE TITLE
Unicode shouldn't be converted

### ISSUE THREAD

**Issue by Xu-Stefan** [dangmai/prettier-plugin-apex#165]
Before format:
`String str = '[\u0000-\u001f]|[\u007f]'`

After format:
`String str = '[-]|[]'`

this is not right. And this will make the changes of the file cannot be preview in the git.

**Comment by dangmai** [comment]
Hi, thank you for the bug report. You're right, it shouldn't transform it that way - I'll fix this soon.

**Comment by dangmai** [comment]
This has been fixed in `master` and will be included in the next release.

Thanks again for the bug report!

**Comment by dangmai** [comment]
Hi, `1.2.0` is out and contains the fix for this.

**Comment by Xu-Stefan** [comment]
Thanks.
