### ISSUE TITLE
Exception happened when I tried to format apex code by using prettier.formatWithCursor method.

### ISSUE THREAD

**Issue by piziliguang** [dangmai/prettier-plugin-apex#1652]
### Self-Troubleshooting Checklist

- [X] Are you running Prettier Apex >= 2.0.0? If Yes, have you gone through the [Upgrade Guide](https://github.com/dangmai/prettier-plugin-apex/wiki/Upgrading-to-Prettier-Apex-v2)?
- [X] Are you running Java >= 11? If No, you need to install a newer Java version.
- [X] Are you running VSCode and recently upgraded Prettier or Prettier Apex? If Yes, have you restarted VSCode after the upgrade?

### Describe your issue

The plugin works well when we use **prettier.format** method to format an apex class. But it failed when we use the **prettier.formatWithCursor** method below.

```
let prettier = await import('prettier'), apexPrettierPlugin = await import('prettier-plugin-apex');
let result = await prettier.formatWithCursor(apexCode, { semi: true, tabWidth: 4, currsorOffset: 10, parser: 'apex', plugins: [apexPrettierPlugin] });
```
It always threw the error below. 
**TypeError: Cannot read properties of undefined (reading 'startIndex')**
<img width="988" alt="image" src="https://github.com/user-attachments/assets/66a09a6f-c41e-458d-a3e6-cdc5f469427d">

![image](https://github.com/user-attachments/assets/f858b78a-d401-4ca2-b2bb-c174e0431b19)

### Prettier options (if any)

```shell
{ semi: true, tabWidth: 4, currsorOffset: 10, parser: 'apex', plugins: [apexPrettierPlugin] }
```

### System Info

```shell
System:
    OS: macOS 15.0
    CPU: (12) arm64 Apple M2 Max
    Memory: 8.15 GB / 32.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 21.0.1 - /usr/bin/javac
    Perl: 5.34.1 - /usr/bin/perl
    Python3: 3.9.6 - /usr/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  npmPackages:
    prettier: ^3.3.3 => 3.3.3 
    prettier-plugin-apex: ^2.1.5 => 2.1.5
```

**Comment by dangmai** [comment]
Hi there, thank you for opening this issue.

Unfortunately this is not actionable from my end. Prettier (the upstream project) doesn't let plugins do range formatting (which is needed to format with cursor) - see my opened issue: https://github.com/prettier/prettier/issues/7639 Once upstream adds the ability for plugins to do range formatting, I'll make sure to add support for it in Prettier Apex.
