### ISSUE TITLE
extra new lines after trailing comment

### ISSUE THREAD

**Issue by xixiaofinland** [dangmai/prettier-plugin-apex#1777]
### Initial Apex code

```apex
class A {
  {
  }
} 

//test
```

### Formatted Apex code

```apex
class A {
  {
  }
} 

//test
```

### Expected Apex code

```apex
class A {
  {
  }
} 

//test
```

### Playground link

https://apex.dangmai.net/#N4Ig9gDgLglmB2BnEAuUEwCcqoCy4GYAaEACzERxRAEMIBTADwFobKA6BTe+AE3szsAxmAC2IEhExgoYEQBtUZKFAjJJNTIgFK6TCSCkx4UAOoxeUUqgAcABhJQaAI3OXrKAEwkArtoAqLsgoAGY08tokeowAkkgCUABixuEAcvQA7vLG9KhQmD70AL4kIvxKQvJsiAAEAII1wAA68DWNLW1FLUU1LS0A9P1Q9JQgRUA

**Comment by xixiaofinland** [comment]
There are two extra new lines after `//test` line.

**Comment by dangmai** [comment]
Indeed that's an issue. Thanks for reporting it!
