### ISSUE TITLE
Annotated Properties on Inner Classes are Indented too Far

### ISSUE THREAD

**Issue by kacrouse** [dangmai/prettier-plugin-apex#18]
See line 4 of the example below, the first line of the property is indented one tab too far. It appears this only happens with annotated properties, not annotated methods.
```
class topLevelClass
    class innerClass {
        @AuraEnabled
            public String someProperty {
            get;
            set;
        }
    }
}
```

**Comment by dangmai** [comment]
Yup that is definitely an issue, thanks for the bug report, I'll take a look at it soon.

**Comment by dangmai** [comment]
I fixed this issue in the `master` branch. This involves changing the format for getter/setter methods as well. Your formatted code will look like this:

```
class topLevelClass
    class innerClass {
        @AuraEnabled
        public String someProperty { get; set; }
    }
}
```
This should land in the next alpha release. You can watch this repository for new releases if you want to test it out then.

Thanks again for your bug report!

**Comment by kacrouse** [comment]
Excellent, thanks Dang! I will test it out when it's released.
