### ISSUE TITLE
Anonymous apex parsing doesn't work

### ISSUE THREAD

**Issue by dcstuff** [dangmai/prettier-plugin-apex#180]
Prettier is attempting to parse anonymous apex as if it were a normal class.

`prettier --write "/path/to/project/anonymous/**/*.cls" --parser apex-anonymous` returns _Error: Unexpected token '[whatever my first anonymous word is]'._

**Comment by dangmai** [comment]
Hi, thank you for the bug report. What version of `prettier-plugin-apex` are you using?

**Comment by dcstuff** [comment]
1.2

**Comment by dangmai** [comment]
Hmm so I just tried this and it works fine on my computer. If possible, could you share what's in your `package.json` file?

Could you also please run `npm ls prettier-plugin-apex` in your project directory? That'll be very helpful.

**Comment by dcstuff** [comment]
```
oom@1.0.0 C:\Users\dc\Documents\dev\Salesforce\OOM
`-- prettier-plugin-apex@1.2.0 
```

```
{
  "name": "oom",
  "version": "1.0.0",
  "description": "This guide helps Salesforce developers who are new to Visual Studio Code go from zero to a deployed app using Salesforce Extensions for VS Code and Salesforce CLI.",
  "main": "index.js",
  "scripts": {
    "test:unit": "sfdx-lwc-jest",
    "test:unit:watch": "sfdx-lwc-jest --watch",
    "test:unit:debug": "sfdx-lwc-jest --debug",
    "prettier": "prettier"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@salesforce/sfdx-lwc-jest": "^0.7.0",
    "prettier": "^1.19.1",
    "prettier-plugin-apex": "^1.2.0"
  }
}
```

**Comment by dangmai** [comment]
Your config file looks good to me, could you do me a favor and run `npm ls -g prettier-plugin-apex`? I want to make sure you don't have a globally installed version that's overriding the locally installed one.

**Comment by dcstuff** [comment]
`-- (empty)

Was pretty sure I had installed it locally.

**Comment by dangmai** [comment]
Hmm in that case I am stumped. I even set up a repository to try to reproduce your issue here, with your `package.json`: https://github.com/dangmai/ppa-180 and it works fine for me. Could you try that one out to see if it works for you? If it does, there's a configuration error somewhere in your repository.

**Comment by dcstuff** [comment]
Ok. Your package works. And I migrated it over to mine, and here is what I discovered.
My folder structure:
**- root > scripts > apex > anonymous1.cls, anonymous2.apex**

My package.json
`"format-anonymous": "prettier --write ./scripts/apex/**/*.apex --parser apex-anonymous"`

When I run `npm run prettier --write ./scripts/apex/**/*.apex --parser apex-anonymous`
I get _No parser could be inferred for file: scripts\apex\anonymous2.apex_

When I run `npm run prettier --write ./scripts/apex/**/*.cls --parser apex-anonymous`
I get _Error: Unexpected token '[my first token]'_

When I run `npm run format-anonymous`...
... it works! And my anonymous2.apex is formatted correctly. Huzzah!

So I guess my only question now is... why does it only work when I run the script as defined in the package.json? Am I running the command wrong from the command line?

**Comment by dangmai** [comment]
I'm glad to hear that it's working for you. Based on your comment, I believe you need to use this (Note the `--` between `npm run prettier` and the rest of the arguments, see the documentation [here](https://docs.npmjs.com/cli/run-script.html)):

```
npm run prettier -- --write ./scripts/apex/**/*.cls --parser apex-anonymous
```

That would also work if you name file your files `.apex` instead of `.cls`.

The issue is that you didn't use the `--`, which is necessary to pass in arguments to npm run scripts.

**Comment by dangmai** [comment]
I closed this issue because it's not an issue with this library, but if you need help setting up `prettier-plugin-apex` with your library feel free to add comments here.

**Comment by dcstuff** [comment]
That was it! I'm glad it was more than a semicolon..
Thanks very much!
