### ISSUE TITLE
Sync on Parser Name with Salesforce VS Code Extension Pack

### ISSUE THREAD

**Issue by dv297** [dangmai/prettier-plugin-apex#201]
Probably my own extension or clarification of #155

The official Salesforce VS Code Extension Pack specifies that the language for all ".apex" files is "apex-anon".

https://github.com/forcedotcom/salesforcedx-vscode/pull/1001/files#diff-2ca79373ff6eff74c3072d6570cb5e9eR205

Because of this, trying to run "Format Document" in VS Code causes the "There is no formatter for 'apex-anon' files installed.

I'm not as familiar with all of the moving pieces between VS Code, Prettier, the VS Code-Prettier extension, and this prettier-plugin-apex, but would changing the parser name from "apex-anonymous" to "apex-anon" allow VS Code to automatically detect the parser and allow formatting of anonymous Apex from VS Code?

**Comment by dangmai** [comment]
Hi,

Thank you for the research, I did not realize Salesforce splits the languages to 2 different parsers, which does explain #155. I _think_ changing the parser name would work, but I'd need a major version bump to follow semver, which I am less enthusiastic about. Also, all users of this library who built their CLI workflows using the current parser name would have their process broken.

@ntotten is there any chance that you guys can change the parser name on your end?

**Comment by dangmai** [comment]
I've released version 1.4.0 that handles this use case, you should be able to format anonymous Apex in VS Code with extension `.apex` now.
