### ISSUE TITLE
Prettier dependency version

### ISSUE THREAD

**Issue by lukecotter** [dangmai/prettier-plugin-apex#211]
Now that v2 of prettier is released does the version in this project need updating?

And are we ok to use v2 even is the dependency in this project is not updated?

https://prettier.io/blog/2020/03/21/2.0.0.html

**Comment by dangmai** [comment]
Hi, thank you for the report. Yes I'm planning to release a minor version that bumps peer dependency with Prettier 2 very soon! Stay tuned 😉

**Comment by dangmai** [comment]
I have released version 1.4.0 with updated peer dependency with Prettier 2.0. Let me know if you run into any issue with it.

**Comment by lukecotter** [comment]
Perfect, thanks for the quick turnaround, I'll give it a test.
