### ISSUE TITLE
soql distance parsing

### ISSUE THREAD

**Issue by mshanemc** [dangmai/prettier-plugin-apex#237]
```sh
# Prettier options (if any):
```
**Input:**

```apex
return [
      SELECT
        id,
        Name,
        Account__c,
        Account__r.Name,
        Description__c,
        City__c,
        Phone__c,
        Street__c,
        Type__c,
        Website__c,
        Zip_Code__c,
        Preferred__c,
        Near_Homeless__c, Homeless__c, Runaway__c, Home_Owner__c, Home_Renter__c,
        DISTANCE(
          Location__c,
          GEOLOCATION(:client.Location__Latitude__s,
            :client.Location__Longitude__s
          ),
          'mi'
        ) dist
      FROM Service__c
      WHERE
        (Minimum_Age__c = null
        OR Minimum_Age__c < :age)
        AND (Maximum_Age__c = null
        OR Maximum_Age__c > :age)
        AND DISTANCE(
          Location__c,
          GEOLOCATION(:client.Location__Latitude__s,
            :client.Location__Longitude__s
          ),
          'mi'
        ) < :defaultMaxDistance
    ];
```

**Actual output:**

["ERROR" - 2:33:27 PM] Error formatting document.
["ERROR" - 2:33:27 PM] No handler found for apex.jorje.data.soql.SelectExpr$SelectDistanceExpr. Please file a bug report.

**Expected output:**
?

**Additional information (please fill this out)**:

OSX catalina 10.15.5 (19F101)
 "prettier-plugin-apex": "^1.4.0"

**Comment by dangmai** [comment]
Thank you for filling the issue, I'll fix this soon!

**Comment by mshanemc** [comment]
thanks for the lovely extension and the error that suggests logging an issue.

**Comment by dangmai** [comment]
I've pushed a fix for this in the `master` branch, I'm anticipating a release in the next couple of days that will contain it.

Thanks again for the report 🔥
