### ISSUE TITLE
TYPEOF SOQL queries should always be on a new line for each group of statements

### ISSUE THREAD

**Issue by paustint** [dangmai/prettier-plugin-apex#244]
TYPEOF SOQL queries collapse into one line, which is extremely difficult to read and does not represent the nested nature of the query. Ideally this would be formatted in a way that is easy to read, just like the Salesforce documentation examples.

https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_typeof.htm

_**NOTE**: Github appears to have better syntax highlighting than VSCode, so this is a lot easier to read on GitHub. If VSCode properly highlighted the syntax then I probably would not have opened this bug as I could have read my code a lot better._

![image](https://user-images.githubusercontent.com/5461649/87728507-6dcb4200-c780-11ea-8e4a-6ac3f8e8d0f8.png)

```json
# Prettier options (if any):
{
  "trailingComma": "none",
  "singleQuote": true,
  "printWidth": 140,
  "overrides": [
    {
      "files": "**/classes/**/*.cls",
      "options": { "tabWidth": 4 }
    },
    {
      "files": "**/lwc/**/*.html",
      "options": { "parser": "lwc", "tabWidth": 4 }
    },
    {
      "files": "*.{cmp,page,component,email}",
      "options": { "parser": "html", "tabWidth": 4 }
    }
  ]
}
```

**Input:**

```apex
List<Foo_User__c> FooUsers = [
  SELECT Id,
      TYPEOF SFDC_Lead__r.Owner
        WHEN User THEN Id, Name, IsActive
        WHEN Group THEN Id, Name, Type
      END
  FROM Foo_User__c
];
```

**Actual output:**

```apex
List<Foo_User__c> FooUsers = [
  SELECT Id,
      TYPEOF SFDC_Lead__r.Owner WHEN User THEN Id, Name, IsActive WHEN Group THEN Id, Name, Type END
  FROM Foo_User__c
];
```

**Expected output:**
```apex
List<Foo_User__c> FooUsers = [
  SELECT Id,
      TYPEOF SFDC_Lead__r.Owner
        WHEN User THEN Id, Name, IsActive
        WHEN Group THEN Id, Name, Type
      END
  FROM Foo_User__c
];
```

**Additional information (please fill this out)**:

- OS: OSX
- Version: 1.4.0
- Prettier version: 2.0.5

**Comment by dangmai** [comment]
Hey, thanks for the bug report. I agree that the current formatting is not ideal, pretty much because I don't use TYPEOF a whole lot in my code 😄 I'll fix it soon. I do like your expected output so that's probably how I'll implement it.

**Comment by dangmai** [comment]
Hi, this has been fixed in the `master` branch and will be included in the next release. Turns out the queries were already broken up correctly if the line is long enough, the only change I made is to make sure it always gets broken up even if the line doesn't exceed `tabWidth`.

Thanks again for the bug report!
