### ISSUE TITLE
Formatting for loop inline SOQL query

### ISSUE THREAD

**Issue by kend77** [dangmai/prettier-plugin-apex#28]
When formatting an inline SOQL query inside of a for loop, a new line is added right after the opening parentheses.

Example Code before prettier:
```java
for (Report rpt: [SELECT Name, DeveloperName, FolderName, Description FROM Report WHERE FolderName = 'Some Folder']) {
			// some other code in here
}
```

Expected output (Seems like a nicer way to format):

```java
for (Report rpt: [
	SELECT Name, DeveloperName, FolderName, Description
	FROM Report
	WHERE FolderName = 'Some Folder'
]) {
	// some other code in here
}
```

Actual:

```java
for (
      Report rpt: [
		SELECT Name, DeveloperName, FolderName, Description
		FROM Report
		WHERE FolderName = 'Some Folder'
	]
) {
			// some other code
}
```

**Comment by dangmai** [comment]
Thank you for the report! I will look into this, though I will have to check the code base to see whether this type of formatting would be consistent with other decisions I've made or not.

**Comment by dangmai** [comment]
I do see the appeal for your preferred output. In fact that's how I formatted that up until a month or so again. The issue with that choice is that it deviates from other `for` conditions and makes maintaining the library more complicated. Consider this block (pretend that we choose a very small `printWidth`):

```
for (Integer i = 0; i < 9; i++) {}
```

This should be broken up like so:

```
for (
  Integer i = 0;
  i < 9;
  i++
) {
}
```

This is the same choice made by Prettier for other built in language. The reasoning is that by adding the newline before the conditional expression, we gain a few characters to fit the condition into. The same thing applies to your case. My guess is that you use a big `tabWidth` (it looks like 4 or so), so it looks the same to you. However, the default `tabWidth` is 2, which does gain us some characters to fit into the line.

**Comment by dangmai** [comment]
This issue keeps nagging me to be honest. After multiple re-considerations I think I'm going to change the way it works to your expected output. The space saving I described in my previous comment IMO doesn't apply to the majority of Apex code, while your expected output saves 1 tab width in a lot of cases.

I will reopen this issue and fix it for the next release.

**Comment by dangmai** [comment]
I've put in a fix for this in `master` and it will be included in the next version.

**Comment by dangmai** [comment]
`1.0.0-rc.5` has been published and contains a fix for this.
