### ISSUE TITLE
Enforcing comment line length?

### ISSUE THREAD

**Issue by codefriar** [dangmai/prettier-plugin-apex#283]
I've been researching the Prettier way of handling things, and its seems that most langauges' don't handle comments. However, it'd be awesome if Prettier-Apex did. Thoughts?

```sh
# Prettier options (if any):
```
**Input**

```apex
/**
 * @description Demonstrates various ways of making Data Manipulation Language (DML) calls
 * Note that this class demonstrates both Database.* methods as well as DML Keywords.
*/
```

**Actual output:**

```apex
/**
 * @description Demonstrates various ways of making Data Manipulation Language (DML) calls
 * Note that this class demonstrates both Database.* methods as well as DML Keywords.
*/
```

**Expected output:**

```apex
/**
 * @description Demonstrates various ways of making Data Manipulation Language 
 * (DML) calls. Note that this class demonstrates both Database.* methods as well
 *  as DML Keywords.
*/
```

**Additional information (please fill this out)**:

- OS: [e.g. Windows/OS X/Ubuntu]

Mac OS Catalina 

- Version: [e.g. 1.0.0]
1.6.0

**Comment by dangmai** [comment]
Hi @codefriar, thank you for the suggestion. I can see the appeal of auto formatting comments, but there are a few obstacles that are non trivial to handle:

- Comments are just a blob of string that was given to us by the parser, they don't have any special semantic meaning whatsover. That means we have write our own parser to handle different types of comments. For example: ApexDoc have different semantics vs standard block comments vs inline comments. Formatting those different comment types will require different approaches.

- For normal code, we have a way to turn off Prettier formatting if the desired result is not the user's satisfaction (`// prettier-ignore`). This does not work out of the box for comments - there is a technical reason for it but it's a bit too complex for me to dive into, let's just say that almost all languages supported by Prettier follow certain conventions when it comes to comment handling and this is not a use case that Prettier comment handling subsystem is built for. This means that if we format the comment wrongly (either semantically or stylistically), there is not really a way for users to turn that off for that particular instance.

I'm not saying doing this is impossible, but it is very difficult and time consuming. I don't see myself spending time on this, but if a PR is opened that can handle all the edge cases and is maintainable I am happy to merge it. I will say though that comment handling in general is very difficult to get right, hence why all other Prettier languages do not even attempt to format comments in the first place.

I'll keep this ticket open for a month or so for exposure if other people want to chime in/contribute to.

**Comment by dangmai** [comment]
I'm closing this ticket because I don't see myself implementing it. If someone wants to pick it up, please feel free to. However, if you do I highly suggest making it into a separate Prettier plugin, so that all of the Prettier ecosystem can use it. Most languages have the same types of comments (blocks/inlines) so something like this would be beneficial for everything else. A word of warning is that comments do not fit into the way Prettier formats things (they are not broken down into smaller AST nodes), so it will be a big challenge.
