### ISSUE TITLE
There is no formatter for 'apex' files installed

### ISSUE THREAD

**Issue by PhilTerz** [dangmai/prettier-plugin-apex#289]
I followed the directions in https://developer.salesforce.com/tools/vscode/en/user-guide/prettier

I am able to run the commands you listed
`prettier --debug-check "/path/to/project/**/*.{trigger,cls}"`
 in the readme and it does format all my classes and is working fine. But I can't trigger a manual format of a document after that, and even though I have the format on save setting enabled it doesn't do anything on save.

When I try to manually format a class (shift option F) I get the error message that. **There is no formatter for 'apex' files installed**. My Editor:Default Formatter setting is set to esbenp.prettier-vscode.

Is this plugin supposed to be compatible for format on save and manual formatting? It's working as expected when I run the commands in terminal, but not in other cases I'd use daily.

**Comment by dangmai** [comment]
Hello, can you paste what's in your `package.json` file please? Also, in your terminal please run these two commands in your project directory and paste the results here:

```
npm ls prettier-plugin-apex
npm ls -g prettier-plugin-apex
```

**Comment by PhilTerz** [comment]
Thanks for the quick reply.

Package.json
{
  "name": "salesforce-app",
  "private": true,
  "version": "1.0.0",
  "description": "Salesforce App",
  "scripts": {
    "lint": "npm run lint:lwc",
    "lint:lwc": "eslint force-app/main/default/lwc",
    "test": "npm run test:unit",
    "test:unit": "sfdx-lwc-jest",
    "test:unit:watch": "sfdx-lwc-jest --watch",
    "test:unit:debug": "sfdx-lwc-jest --debug",
    "test:unit:coverage": "sfdx-lwc-jest --coverage",
    "prettier": "prettier --write \"**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}\"",
    "prettier:verify": "prettier --list-different \"**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}\""
  },
  "devDependencies": {
    "@prettier/plugin-xml": "^0.7.0",
    "@salesforce/eslint-config-lwc": "^0.4.0",
    "@salesforce/sfdx-lwc-jest": "^0.7.0",
    "eslint": "^5.16.0",
    "prettier": "^1.19.1",
    "prettier-plugin-apex": "^1.0.0"
  }
}

npm ls prettier-plugin-apex
salesforce-app@1.0.0 /Users/philipterzic/Documents/XXXXX
└── (empty)

npm ls -g prettier-plugin-apex
/usr/local/lib
└── prettier-plugin-apex@1.7.0

**Comment by dangmai** [comment]
Can you run `npm ls prettier-plugin-apex` inside the folder with the `package.json` file?

**Comment by PhilTerz** [comment]
Yes, my packager.json is at the root of the SF Project folder

`npm ls prettier-plugin-apex`
salesforce-app@1.0.0 /Users/philipterzic/Documents/XXXXX
└── (empty)

**Comment by dangmai** [comment]
Hmm so that's the reason why it's not working. You have Prettier Apex installed globally but not at the local level, I think the Prettier VS Code extension only works if Prettier Apex is installed on the local level.

If you use the command in the [document](https://developer.salesforce.com/tools/vscode/en/user-guide/prettier/#installation) that you link, it should have been installed locally. Can you re-do the steps in that document?

**Comment by PhilTerz** [comment]
I see, I'll go through that document again to try to reinstall.

In the Prettier Apex readme it says we can install globally or locally so I was following that.

Thanks for the help.

**Comment by dangmai** [comment]
I totally understand. Prettier Apex can be used both globally and locally, but the VSCode Prettier extension is a separate project to this and it has its own assumption about the location Prettier Apex can be installed.

I'll close this ticket for now, feel free to ask more questions if you still cannot get it to work.
