### ISSUE TITLE
Ternary statement formatting

### ISSUE THREAD

**Issue by kend77** [dangmai/prettier-plugin-apex#29]
When dealing with ternary expressions, formatting does not look like the same code in JS.

Expected:

```java
String someString = 'Yes'
someFuntionCall(
     someString == 'Yes'
          ? SomeClass.someMethod()
          : SomeOtherClass.someOtherMethod()
);
```
Actual: 
```java
String someString = 'Yes';
someFuntionCall(
	someString ==
	'Yes' ? SomeClass.someMethod() : SomeOtherClass.someOtherMethod()
);
```

**Comment by dangmai** [comment]
Thank you for the bug report, I agree with your expected output formatting and will hopefully have a fix for this soon

**Comment by dangmai** [comment]
This has been fixed in `master` and will be included in the next release.

Thanks again for the bug report!

**Comment by dangmai** [comment]
FYI I have released the new version that contains the fix for this.
