### ISSUE TITLE
Support `prettier-ignore` directive

### ISSUE THREAD

**Issue by dangmai** [dangmai/prettier-plugin-apex#3]
In case the user wants to keep certain format for a block of code, let's respect the `prettier-ignore` directive that Prettier supports. This is only about the next node ignore, not the range ignore since I don't see that being very useful for Apex.

**Comment by dangmai** [comment]
Moving this out of `1.0.0-rc1` project. I think this is a good idea but it does take some time to implement, maybe we can do it for `1.0.0`.

**Comment by arvindkgs** [comment]
Please add this feature. For certain custom repeated format that we have in our code (especially for frequently occurring cases like Field accessibility check before executing SOQL)  we would like the multiple checks on fields to be in a single if condition. We format it like -
`if (!SObjectType.Attribute__c.fields.Name.isAccessible() ||
            !SObjectType.Attribute__c.fields.Display_on_Actions_Tab__c.isAccessible() ||
            !SObjectType.Attribute__c.fields.Display_Order__c.isAccessible() ||
            !SObjectType.Attribute__c.fields.Icon__c.isAccessible() ||
            !SObjectType.Action__c.fields.Name.isAccessible() ||
            !SObjectType.Action__c.fields.Description__c.isAccessible() ||
            !SObjectType.Action__c.fields.Translation_Index__c.isAccessible() ||
            !SObjectType.Action__c.fields.State__c.isAccessible() ||
            !SObjectType.Action__c.fields.Display_Tab__c.isAccessible() ||
            !SObjectType.Action__c.fields.Display_Tile__c.isAccessible() ||
            !SObjectType.Action__c.fields.Action_Type_Attribute__c.isAccessible() ||
            !SObjectType.Action__c.fields.Tile_Type_Attribute__c.isAccessible() ||
            !SObjectType.Action__c.fields.From_Date__c.isAccessible() ||
            !SObjectType.Action__c.fields.To_Date__c.isAccessible() ||
            !SObjectType.Action__c.fields.Parent__c.isAccessible() ||
            !SObjectType.Action__c.fields.RecordTypeId.isAccessible()) `

But running prettier formats like-
`if (!SObjectType.Attribute__c.fields.Name.isAccessible() || !SObjectType.Attribute__c.fields.Display_on_Actions_Tab__c.isAccessible() || !SObjectType.Attribute__c.fields.Display_Order__c.isAccessible() || !SObjectType.Attribute__c.fields.Icon__c.isAccessible() || !SObjectType.Action__c.fields.Name.isAccessible() || !SObjectType.Action__c.fields.Description__c.isAccessible() || !SObjectType.Action__c.fields.Translation_Index__c.isAccessible() || !SObjectType.Action__c.fields.State__c.isAccessible() || !SObjectType.Action__c.fields.Display_Tab__c.isAccessible() || !SObjectType.Action__c.fields.Display_Tile__c.isAccessible() || !SObjectType.Action__c.fields.Action_Type_Attribute__c.isAccessible() || !SObjectType.Action__c.fields.Tile_Type_Attribute__c.isAccessible() || !SObjectType.Action__c.fields.From_Date__c.isAccessible() || !SObjectType.Action__c.fields.To_Date__c.isAccessible() || !SObjectType.Action__c.fields.Parent__c.isAccessible() || !SObjectType.Action__c.fields.RecordTypeId.isAccessible()) {`

**Comment by dangmai** [comment]
Hi, this will be added, just not for the `1.0.0-rc1` milestone. I need to prioritize things in order to push the release out sooner.

**Comment by arvindkgs** [comment]
Thank you. I will try it out.
