### ISSUE TITLE
Using the standalone parser removes type declarations from loops

### ISSUE THREAD

**Issue by shliachtx** [dangmai/prettier-plugin-apex#308]
```sh
--apex-standalone-parser built-in
```

**Input:**

```apex
for (List<Sobject> sobjList : results) {
```

**Actual output:**

```apex
for ( sobjList : results) {
```

**Expected output:**

```apex
for (List<Sobject> sobjList : results) {
```

**Additional information (please fill this out)**:

- OS: Windows
- Version: 1.7.0

**Comment by dangmai** [comment]
Hi, thank you for the bug report. Can you make sure you're running the same version of the parsing server and the client? Here are a few commands you can run (run these inside your project directory):

```
npm ls prettier-plugin-apex
npm ls -g prettier-plugin-apex
```

Here's another thread from someone else who had similar issue to you: https://github.com/dangmai/prettier-plugin-apex/issues/253 It will be great if we can get to the bottom of this.

**Comment by shliachtx** [comment]
Updating the global version of the plugin (and prettier) seems to have fixed the issue. Thank you!

**Comment by dangmai** [comment]
Awesome, I'm glad you fixed the issue!
