### ISSUE TITLE
'Unexpected token' error for Safe Navigation Operator

### ISSUE THREAD

**Issue by ChristianMenzinger** [dangmai/prettier-plugin-apex#323]
Parser does not handle safe navigation operator correctly.

**Input:**

```apex
public with sharing class TestFormatting {
    public String testFormattingWithSafeNavigation() {
        return [SELECT Name FROM Account Limit 1]?.Name;
    }
}
```

**Actual output:**
Error: Unexpected token '.'.. Syntax(error = UnexpectedToken(loc = (3, 51, 38, 39), token = '.'))

**Expected output:**
No syntax error for a valid Apex statement

**Additional information (please fill this out)**:
More information about the Safe Navigation Operator and code samples:
https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_SafeNavigationOperator.htm

**Comment by dangmai** [comment]
Hi, what version of Prettier Apex are you running? 1.7.0 should handle Safe Navigation already.

**Comment by ChristianMenzinger** [comment]
Thanks for the quick reply. My bad, I thought I was running "latest" but indeed I had a fixed older version.

Thank you for all the effort you are spending on this project - highly appreciated!
