### ISSUE TITLE
axios vulnerability

### ISSUE THREAD

**Issue by jdcrensh** [dangmai/prettier-plugin-apex#333]
This project uses a vulnerable version of axios. Please update to `^0.21.1`

https://www.npmjs.com/advisories/1594

**Comment by dangmai** [comment]
Hi, thanks for the bug report. This is already fixed in https://github.com/dangmai/prettier-plugin-apex/commit/f6892836c24fa116a70c27a764a51c5e84a7155e, and it will be included in the next release. I'm planning to fix one more formatting bug before releasing it.

**Comment by btamburrino** [comment]
@dangmai Hi, I was wondering if you had an ETA on the next release? Your last update was 3 weeks ago and we just had the axios vulnerability warning pop up in our project and it's making people above me skittish.

**Comment by dangmai** [comment]
Hi @btamburrino I haven't had the chance to fix the last formatting bug that I wanted to include in the next release yet, so I think I'll just cut a new release some time this week without it. At least that's the plan - there are some logistical challenges with this new release (moving from Travis to Github Actions for instance) that might delay it.

Out of curiosity do you know how the vulnerable version of axios get pulled into your dependencies? There are 2 paths that can lead to axios from Prettier Apex, one is a direct dependency from Prettier Apex, and (I believe) one is via `wait-on`. If it is the former, maybe you can just relock your `package-lock.json` or `yarn.json` file to get the new axios version. If it's the latter then you'll have to wait for a new Prettier Apex version.

**Comment by btamburrino** [comment]
@dangmai We have prettier-plugin-apex in our devDependencies. I've been looking into how to manipulate package-lock to get it to work and will continue down that path, but we're also good with waiting for a new release later this week. (We aren't using yarn so no "resolutions" area in package.json.) Thanks for your response!

**Comment by dangmai** [comment]
I've published `1.8.0` to NPM, please try it out and let me know if you have any issue with it.

**Comment by btamburrino** [comment]
@dangmai Looks good here so far, thanks!

**Comment by jdcrensh** [comment]
@dangmai Looks good to me. Thank you.
