### ISSUE TITLE
Backslash added to LIKE expression only: \_

### ISSUE THREAD

**Issue by shunkosa** [dangmai/prettier-plugin-apex#340]
```sh
prettier --write AccountController.cls
```

**Input:**

```apex
public with sharing class AccountController {
  @AuraEnabled(cacheable=true)
  public static Account getSingleAccount() {
    return [SELECT Name FROM Account WHERE Name LIKE '\_'];
  }
}

```

**Actual output:**

```apex
public with sharing class AccountController {
  @AuraEnabled(cacheable=true)
  public static Account getSingleAccount() {
    return [SELECT Name FROM Account WHERE Name LIKE '\\_'];
  }
}
```

**Expected output:**

```apex
public with sharing class AccountController {
  @AuraEnabled(cacheable=true)
  public static Account getSingleAccount() {
    return [SELECT Name FROM Account WHERE Name LIKE '\_'];
  }
}
```

**Additional information (please fill this out)**:

- OS: [e.g. Windows/OS X/Ubuntu] Mac OS X 10.15.7
- Version: [e.g. 1.0.0] 1.8.0
- Reference: https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_quotedstringescapes.htm

**Comment by dangmai** [comment]
Thank you for the bug report. You are right, I can reproduce this on my machine - I will try to fix this asap. In the meantime you can put a `// prettier-ignore` line before the query so that Prettier stops formatting it incorrectly.

**Comment by dangmai** [comment]
Hi, this has been fixed in `master` and will be included in the next release. Thanks again for the bug report.
