### ISSUE TITLE
Flagging invocable methods as "makes callout" is not supported by the plugin

### ISSUE THREAD

**Issue by albarivas** [dangmai/prettier-plugin-apex#341]
```sh
# Prettier options (if any):
```

**Input:**

[New feature from Spring 21](https://help.salesforce.com/articleView?id=release-notes.rn_apex_flow_flag_invocable_methods_callouts.htm&release=230&type=5):

```apex
@InvocableMethod(callout=true)
```

**Actual output:**

![Screenshot 2021-02-08 at 13 10 04](https://user-images.githubusercontent.com/12017842/107218035-5a7b0f00-6a0f-11eb-909b-e44af575d339.png)

**Expected output:**

No failure

**Additional information (please fill this out)**:

- OSX

**Comment by albarivas** [comment]
Also, adding /* prettier-ignore */ or // prettier-ignore before the line is not ignoring it

**Comment by albarivas** [comment]
Not an issue of the plugin, the code doesn't deploy itself

**Comment by dangmai** [comment]
Hi, thank you for opening the issue. Can you confirm which version of `prettier-plugin-apex` you are using? On my machine invocable methods with callout are formatted correctly with the latest version of Prettier Apex (1.8.0)

**Comment by dangmai** [comment]
It will also be very beneficial if you can attach the piece of code that is failing so we can debug it further - here are the test cases I added for InvocableMethod which run fine: https://github.com/dangmai/prettier-plugin-apex/commit/9d8bef7da4a838163de3e6d11050000c73f4006c maybe you can compare your code to that and see if there's a difference?

**Comment by pozil** [comment]
Sorry @dangmai this was a mistake on our end.
@albarivas you had a comma between the annotation parameters:
```
@InvocableMethod(callout=true, label='Geocode address')
public static List<Coordinates> geocodeAddresses(List<GeocodingAddress> addresses) {
```

**Comment by albarivas** [comment]
Yeah, sorry, my bad, closing the issue

**Comment by dangmai** [comment]
No problem, I'm glad this gets sorted out quickly.
