### ISSUE TITLE
Error formatting `when` statment with objets

### ISSUE THREAD

**Issue by gabc** [dangmai/prettier-plugin-apex#360]
```sh
# Prettier options (if any):
npm run prettier -- --write "FileName.cls"
```

**Input:**

```apex
    switch on var {
      when Static.Information {
        System.debug('stuff');
      }
    }
```

**Actual output:**

```apex
    switch on var {
      when Static,Information {
        System.debug('stuff');
      }
    }
```

**Expected output:**

```apex
    switch on var {
      when Static.Information {
        System.debug('stuff');
      }
    }
```

**Additional information (please fill this out)**:

- OS: Windows 10
- Version: 6.14.6

**Comment by dangmai** [comment]
Hi, thank you very much for the bug report. This is definitely an issue with the current code, I'll fix it and release it very soon.

**Comment by gabc** [comment]
Thank you for the quick response and the fix! 🚀

**Comment by dangmai** [comment]
No problem, version `1.9.1` is now published on NPM, so you can upgrade to it 😄
