### ISSUE TITLE
This is probably not a problem with npm. There is likely additional logging output above.

### ISSUE THREAD

**Issue by aceace3** [dangmai/prettier-plugin-apex#367]
Hi DangMai,

Thanks for your formatting tool! My english is not good, i will try my best to describe the issue.
flow is my input:
```sh
npm run prettier -- --write
```
this is my package.json
```apex
 "prettier": "prettier --write '/Users/XXX/Documents/XXX/XXX/force-app/main/default/classes/XXXController.cls'",
```

then i can saw the flow error:
```apex
npm ERR! code ELIFECYCLE
npm ERR! errno 2
...
npm ERR! Failed at the XXX@0.1.0 prettier script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
i use 'XXX' instead of my company info.
hope you can give me some advices, thanks!

- OS: [e.g. OS X]
- Version: [e.g. 1.0.0]

**Comment by dangmai** [comment]
Hi,

If you set up your `package.json` like that, then you need to run this command:

```
npm run prettier
```
