### ISSUE TITLE
Run prettier error

### ISSUE THREAD

**Issue by aceace3** [dangmai/prettier-plugin-apex#368]
Hi, DangMai,

First of all, Thank you for your plugin!
But i met some errors..

Here is my package.json:
```
"prettier": "prettier --write '/Users/xxx/xxx/xxx.cls'",
```

Here is my input:
```sh
npm run prettier -- --write
```

And here is my error message, i don't know why.
The same code other people can run correctly.
```
npm ERR! Failed at the kayak-full@1.0.0 prettier script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Hope you can give me some advices please.

Thanks,
aceace3

- OS: [e.g. OS X]

**Comment by dangmai** [comment]
Hi, did you try out my comment in this duplicated issue yet? https://github.com/dangmai/prettier-plugin-apex/issues/367 I don't see any change to your package.json or to your input. If you try that and run into other issues please comment on either this issue or #367, don't open another one. I also recommend Salesforce guide here https://developer.salesforce.com/tools/vscode/en/user-guide/prettier/ to set up Prettier.

**Comment by aceace3** [comment]
> Hi, did you try out my comment in this duplicated issue yet? #367 I don't see any change to your package.json or to your input. If you try that and run into other issues please comment on either this issue or #367, don't open another one. I also recommend Salesforce guide here https://developer.salesforce.com/tools/vscode/en/user-guide/prettier/ to set up Prettier.

Oh sorry, i missed the #367 reply. I tried 'npm run prettier', but occur same error. I had see the Salesforce guide, but didn't resolve..
