### ISSUE TITLE
Single lined if statements get formatted to multi lined if but without curly braces

### ISSUE THREAD

**Issue by malloryw** [dangmai/prettier-plugin-apex#370]
```sh
prettier --write "src/**/*.{cls,trigger}"

.prettierrc
{
    "trailingComma": "none",
    "printWidth": 120,
    "tabWidth": 4,
    "semi": false,
    "singleQuote": true,
    "apexInsertFinalNewline": false,
    "overrides": [
        {
            "files": "src/lwc/**/*.html",
            "options": { "parser": "lwc" }
        },
        {
            "files": "src/**/*.{cmp,page,component}",
            "options": { "parser": "html" }
        }
    ]
}
```

**Input:**

```apex
if (something) continue;
```

**Actual output:**

```apex
if (something)
    continue;
```

**Expected output:**

```apex
if (something) {
    continue;
}
```
The reason for my proposed expected output is because of these sources:
- https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used
- https://pmd.github.io/latest/pmd_rules_apex_codestyle.html#ifstmtsmustusebraces

**Additional information (please fill this out)**:

- OS: OSX
- Version: 1.9.1

**Comment by dangmai** [comment]
Hi, thank you for opening the bug report. This issue has been brought up before - see https://github.com/dangmai/prettier-plugin-apex/issues/74, and it's one of the design philosophy from Prettier (the upstream project) that I'm simply inheriting for this project.
