### ISSUE TITLE
[error]  at parseTextWithSpawn

### ISSUE THREAD

**Issue by AllanOricil** [dangmai/prettier-plugin-apex#394]
![image](https://user-images.githubusercontent.com/55927613/124803157-2446aa80-df2f-11eb-87d7-1d6df117d485.png)

I followed this guide to install it

https://developer.salesforce.com/tools/vscode/en/user-guide/prettier/

and this is my package.json with the scripts that I use to run prettier. These errors happen when I run `npm run prettier`

````json
{
    "name": "salesforce-app",
    "private": true,
    "version": "1.0.0",
    "description": "Salesforce App",
    "scripts": {
        "lint": "npm run lint:lwc && npm run lint:aura",
        "lint:aura": "eslint salesforce_sfdx/**/aura/**",
        "lint:lwc": "eslint salesforce_sfdx/**/lwc/**",
        "test": "npm run test:unit",
        "test:unit": "sfdx-lwc-jest",
        "test:unit:watch": "sfdx-lwc-jest --watch",
        "test:unit:debug": "sfdx-lwc-jest --debug",
        "test:unit:coverage": "sfdx-lwc-jest --coverage",
        "prettier": "prettier --write \"**/*.{cls,cmp,component,css,html,js,md,page,trigger,xml,yaml,yml}\"",
        "prettier:verify": "prettier --list-different \"**/*.{cls,cmp,component,css,html,js,md,page,trigger,xml,yaml,yml}\""
    },
    "devDependencies": {
        "@prettier/plugin-xml": "^0.12.0",
        "@salesforce/eslint-config-lwc": "^0.7.0",
        "@salesforce/eslint-plugin-aura": "^1.4.0",
        "@salesforce/sfdx-lwc-jest": "^0.14.0",
        "eslint": "^7.6.0",
        "eslint-config-prettier": "^6.11.0",
        "husky": "^4.2.1",
        "lint-staged": "^10.0.7",
        "prettier": "2.3.2",
        "prettier-plugin-apex": "1.10.0"
    },
    "husky": {
        "hooks": {
            "pre-commit": "lint-staged"
        }
    },
    "lint-staged": {
        "**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}": [
            "prettier --write"
        ],
        "**/{aura|lwc}/**": [
            "eslint"
        ]
    }
}

````

**Comment by dangmai** [comment]
Most likely there's an issue with your Java version (Prettier Apex only supports Java >= 11) - please see https://github.com/dangmai/prettier-plugin-apex/issues/392 or https://github.com/dangmai/prettier-plugin-apex/issues/392 to get some idea on how to debug this further, currently the screenshot is not enough for me to know 100% what the issue is.

**Comment by AllanOricil** [comment]
Yes, Im using Java 8. Let me change to 11 and try again.

**Comment by AllanOricil** [comment]
@dangmai you are right. i just changed to java 11 and now everything is working. Thanks

![image](https://user-images.githubusercontent.com/55927613/124811906-61179f00-df39-11eb-90b4-51eeb4154aa5.png)

**Comment by dangmai** [comment]
I'm glad to hear it's working now!

**Comment by inconsolableanki** [comment]
how to change java 11 from java 4 please help

**Comment by nadayzsolt** [comment]
in my case after the Java version's path was found by Java Control Panel, i had to run 'npm update' in the terminal, to make prettier work
