### ISSUE TITLE
Can't format Apex code with Prettier Apex installed globally

### ISSUE THREAD

**Issue by Diabolux** [dangmai/prettier-plugin-apex#397]
Hi,

I am trying to install Prettier Apex to be able to format code with shortkey combinaison alt+shift+f but this is not working.
I've installed JDK 11, npm version 7.19.1, node version 16.5.0 and tried to install Prettier Apex globally with this line of code : 
`npm install --global prettier prettier-plugin-apex`
But when I'm in my project and do `npm ls prettier-plugin-apex`, I get "empty". So when I'm trying to format the code, I have an error telling me that no formatter has been installed for Apex files.
Did I miss something ?

**Comment by dangmai** [comment]
Hi, are you using Prettier Apex inside VSCode? If so you have to install it locally, because the VSCode plugin does not support globally-installed plugins. Follow this tutorial if that's the case: https://developer.salesforce.com/tools/vscode/en/user-guide/prettier/

**Comment by Diabolux** [comment]
Ok thanks. I've done some tests and I can format my code if I installed it locally in the folder that contains all my projects. With this trick, I don't need to install locally in every projects

Thanks for your help :)
