### ISSUE TITLE
Public package on NPM

### ISSUE THREAD

**Issue by dangmai** [dangmai/prettier-plugin-apex#4]
This tracks the progress of publishing `prettier-plugin-apex` on NPM. Here are the tasks that still need to be done:

- [x] Contact @jdcrensh about package availability on NPM.
- [x] Publish placeholder package.
- [x] Wait for Prettier 1.15 to be released. We rely on a few utility methods in this release.
- [ ] Write blog post
- [ ] Publish rc1 package.

**Comment by jdcrensh** [comment]
@dangmai what's your npm username so I can transfer ownership?

**Comment by dangmai** [comment]
Hey @jdcrensh I emailed you my username. Thanks for your help!

**Comment by jdcrensh** [comment]
@dangmai I've added you as an owner to the npm package

**Comment by dangmai** [comment]
Great, thank you @jdcrensh

**Comment by dangmai** [comment]
Closing this ticket since the NPM package has been published
