### ISSUE TITLE
Unexpected newline in compound expression with inline SOQL

### ISSUE THREAD

**Issue by boxfoot** [dangmai/prettier-plugin-apex#40]
I'm honestly not sure what I expect the formatting to be here, but the hanging `0` at the end is really odd.

```java
// input:
Boolean hasPrivateReports = (Integer) ([
	SELECT COUNT(Id) num
	FROM Report
	WHERE OwnerId = :UserInfo.getUserId()
]).get(0).get('num') > 0;

// current output - see newline at end
Boolean hasPrivateReports = (Integer) ([
	SELECT COUNT(Id) num
	FROM Report
	WHERE OwnerId = :UserInfo.getUserId()
]).get(0).get('num') > 
0;
```

**Comment by dangmai** [comment]
That's very interesting. I agree that the output does look odd, but it might not be an easy fix. Let me see what I can do

**Comment by dangmai** [comment]
I have fixed this in `master`, it will be available in the next release some time this or next week.

Thanks again for the report!

**Comment by dangmai** [comment]
FYI I have released the new version that contains the fix for this.
