### ISSUE TITLE
prettier-ignore does not work for if/else spacing

### ISSUE THREAD

**Issue by no-stack-dub-sack** [dangmai/prettier-plugin-apex#464]
Hi, thanks for your great work on this plugin. Just wanted to document the following issue where prettier-ignore doesn't respect not-formatting if/else chains when you'd like to separate long and complex if/else chains by spaces for (arguably) better organization of the code. Thanks!

**Input:**

```apex
if (someCondition) {
  System.debug('foo');
}

// prettier-ignore
else if (someOtherCondition) {
  System.debug('bar');
}
```

**Actual output:**

```apex
if (someCondition) {
  System.debug('foo');
} else if (someOtherCondition) {
  // prettier-ignore
  System.debug('bar');
}
```

**Expected output:**

```apex
if (someCondition) {
  System.debug('foo');
}

// prettier-ignore
else if (someOtherCondition) {
  System.debug('bar');
}
```

**Additional information (please fill this out)**:

- OS: Windows
- Version: 1.10.0

Using VS Code format on save

**Comment by dangmai** [comment]
Hi, thank you for raising this issue. Comments in general are pretty difficult to deal with, especially ones that come in between blocks like this one. I'll see what I can do about it.

**Comment by no-stack-dub-sack** [comment]
Thanks @dangmai for the quick feedback. Since there were a couple of comments that could have been interpreted as being "in between blocks" in my original example I updated my OP to make sure we're on the same page (which I think we are, but just in case I've edited for extra clarity).

Thanks again.

**Comment by dangmai** [comment]
Support for prettier-ignore in the middle of If-Else blocks has been added in `master`, it will be included in the next version. Thank you again for raising this issue.

**Comment by no-stack-dub-sack** [comment]
Awesome! Thanks!
