### ISSUE TITLE
Using "Safe Navigation Operator" will cause formatter error

### ISSUE THREAD

**Issue by MaherSaleem** [dangmai/prettier-plugin-apex#482]
```sh
# Prettier options (if any):
```

**Input:**

```apex
// code snippet
```

**Actual output:**
![image](https://user-images.githubusercontent.com/14930756/154209846-8cf111c6-b86c-42e0-89be-26116fb4aefe.png)

**Expected output:**
`it should format normally`

**Additional information (please fill this out)**:

- OS:  Windows
- Version: [e.g. 1.0.0]

**Comment by dangmai** [comment]
Hi, this likely means you're using a very old version of Prettier Apex. Please upgrade to the newest version and try again.
