### ISSUE TITLE
Error on formatting

### ISSUE THREAD

**Issue by fracarma** [dangmai/prettier-plugin-apex#507]
Error on running prettier:

```
status Error: LinkageError occurred while loading main class net.dangmai.serializer.Apex
        java.lang.UnsupportedClassVersionError: net/dangmai/serializer/Apex has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 54.0
```

Java version:

```
% java -version   
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```
It looks like my Runtime Environment is 18.3 so I'm not sure why this is failing. Any thoughts?

**Additional information**:

- OS: MacOS
- Version: 12.2.1

**Comment by dangmai** [comment]
Hi, this library only supports Java >= 11. Please see the requirement here: https://github.com/dangmai/prettier-plugin-apex#requirements

**Comment by dangmai** [comment]
I can see where the confusion comes from though, the version you need to look at is on the 1st line of the output, the SE Runtime Environment is a different concept altogether.

**Comment by dangmai** [comment]
I'm glad to hear it's working! Yeah I agree with you it's very confusing.
