### ISSUE TITLE
Feature Request: Allow SOQL queries that are shorter than printWidth to be formatted over many lines

### ISSUE THREAD

**Issue by no-stack-dub-sack** [dangmai/prettier-plugin-apex#511]
This is more of a feature request than an issue with any existing formatting rules: I believe that prettier )for JS/TS) used to enforce their rules about objects being on one line if they fell under print width. For example, if you typed:

```js
const obj = {
  foo: 1,
  bar: 2,
}
```
Prettier used to unconditionally format it as:

```js
const obj = { foo: 1, bar: 2 }
```
Since of course this would fall under the printWidth limit.

However, at some point they started letting you choose. If the object is under the limit, they just took the cue from the developer. If they type it on one line, they leave it alone. If they type it over multiple lines, they leave it alone. I'm wondering if something similar can be done for SOQL queries without having to use the `// prettier-ignore` escape hatch.

It may be desirable, on a case-by-case basis, to have some queries formatted over multiple lines.

For example:

**Input:**

```apex
// this example falls under the printWidth limit of 100, so will be auto-formatted
// but it would be nice to be able to opt out of this if the developer writes the query over multiple lines
List<NS__Foo__c> foos = [
  SELECT Id, Foo__c, Bar__c, Baz__c
  FROM NS__Foo__c
  WHERE Baq__c = TRUE
];
```

**Actual output:**

```apex
List<NS__Foo__c> foos = [SELECT Id, Foo__c, Bar__c, Baz__c FROM NS__Foo__c WHERE Baq__c = TRUE];
```

**Expected output:**

```apex
List<NS__Foo__c> foos = [
  SELECT Id, Foo__c, Bar__c, Baz__c
  FROM NS__Foo__c
  WHERE Baq__c = TRUE
];
```

**Additional information**:

- OS: Windows 10
- Version: 10.0.19044 Build 19044

Thanks for considering this!

**Comment by dangmai** [comment]
Hi, thank you for raising this. I can see where you're coming from, and at times I have thought about changing the behavior to the one that you mention. I think I do want to go there eventually, but right now I have some stuff in my personal life to take care of, so I will keep this in the backlog as something to eventually work on.

**Comment by no-stack-dub-sack** [comment]
Thank you for considering it! And of course, that stuff must always come first. Thank you for the good work you do. I'll look forward to it if and when you get around to it.

All the best.

**Comment by dangmai** [comment]
This is now implemented in `master` and will be included in the next release. Thanks again for the request.

**Comment by dangmai** [comment]
There is no fixed release cadence for this library, generally I try to release it when there's "enough" for a release. For this next one, I'm hoping I can get it out in the couple of weeks. There is currently a formatting issue in which formatted comments in certain scenarios are not stable (i.e. the 1st format and the 2nd format are different), once it's fixed I'll release the new version.

**Comment by no-stack-dub-sack** [comment]
Great, I'll keep an eye out for it

**Comment by no-stack-dub-sack** [comment]
Sweet! This works great, especially handy inside `Map<Id, Sobject>` constructors.
