### ISSUE TITLE
[Feature Request] support prettier-ignore on same line

### ISSUE THREAD

**Issue by no-stack-dub-sack** [dangmai/prettier-plugin-apex#567]
I know you have a lot going on, so feel free to treat this request with the lowest priority, but just thought I'd raise this as a suggestion / feature request. Prettier for JS behaves this way, but I do realize in some cases you've made a conscious choice to deviate from the upstream default behaviors.

I think this is more of a visual thing. Putting prettier-ignore above the line, in this case, would visually break up an otherwise consistently formatted block of code.

Thanks for your consideration!

P.S. if you're open to contributions and there's any low-hanging fruit as you convert the codebase to TypeScript I'd be more than happy to contribute back to the project. 
 
```sh
# Prettier options (if any):
printWidth: 80
```

**Input:**

```apex
    System.debug('[SomeDebugMessage] Error_Log__c.Message__c = ' + log.Message__c);
    System.debug('[SomeDebugMessage] Error_Log__c.Stack_Trace__c = ' + log.Stack_Trace__c);
    System.debug('[SomeDebugMessage] Error_Log__c.Exception_Type__c = ' + log.Exception_Type__c); // prettier-ignore
    System.debug('[SomeDebugMessage] Error_Log__c.Developer_Notes__c = ' + log.Developer_Notes__c); // prettier-ignore
```

**Actual output:**

```apex
    System.debug('[SomeDebugMessage] Error_Log__c.Message__c = ' + log.Message__c);
    System.debug('[SomeDebugMessage] Error_Log__c.Stack_Trace__c = ' + log.Stack_Trace__c);
    System.debug(
      '[SomeDebugMessage] Error_Log__c.Exception_Type__c = ' + log.Exception_Type__c
    ); // prettier-ignore
    System.debug(
      '[SomeDebugMessage] Error_Log__c.Developer_Notes__c = ' + log.Developer_Notes__c
    ); // prettier-ignore
```

**Expected output:**

```apex
    System.debug('[SomeDebugMessage] Error_Log__c.Message__c = ' + log.Message__c);
    System.debug('[SomeDebugMessage] Error_Log__c.Stack_Trace__c = ' + log.Stack_Trace__c);
    System.debug('[SomeDebugMessage] Error_Log__c.Exception_Type__c = ' + log.Exception_Type__c); // prettier-ignore
    System.debug('[SomeDebugMessage] Error_Log__c.Developer_Notes__c = ' + log.Developer_Notes__c); // prettier-ignore
```

**Additional information (please fill this out)**:

- OS: Windows
- Version:1 .10.0

**Comment by no-stack-dub-sack** [comment]
Also, while on the topic of `prettier-ignore`, here's another weird one I noticed:

**Input:**

```apex
    // prettier-ignore
    List<Integer> l = new List<Integer>{1,2,3,4,5};

    System.debug('This line gets removed 👆');
```

**Output:**

```apex
    // prettier-ignore
    List<Integer> l = new List<Integer>{1,2,3,4,5};
    System.debug('This line gets removed 👆');
```

The new line after a `prettier-ignored` line is removed which seems unexpected.

**Comment by dangmai** [comment]
I didn't see your comment about the removed newline before I pushed the fix for the original issue. Do you mind creating a new issue for it?

For the original issue, I realize that early on in the project I only allow leading `prettier-ignore` comments, because at that time comment handling was a nuisance to deal with and I didn't know how to handle trailing `prettier-ignore` in a stable manner. But it looks like at this point I can safely enable that - at least all my test cases still pass 😸

**Comment by dangmai** [comment]
Actually your second request is pretty difficult to implement right now, because Prettier core does not have a hook for me to customize printing ignored nodes. There's already a ticket upstream to add that, so when it's implemented I'll tackle the issue. It seems pretty minor tbh.

**Comment by no-stack-dub-sack** [comment]
Sure - with this being the case, do you still want me to open a new ticket to track it? Like you said, its pretty minor, but just figured I'd bring it up while we were on the topic of `prettier-ignore`.

**Comment by dangmai** [comment]
No need to! I'll keep it on my list of future to-dos.

**Comment by ImNotARealUser** [comment]
> No need to! I'll keep it on my list of future to-dos.

Hey @dangmai, just curious if there's been any traction on this. I know it seems minor but it is quite pesky at times. Obviously not a major priority but figured I'd check in. Thanks!

**Comment by dangmai** [comment]
> > No need to! I'll keep it on my list of future to-dos.
> 
> Hey @dangmai, just curious if there's been any traction on this. I know it seems minor but it is quite pesky at times. Obviously not a major priority but figured I'd check in. Thanks!

I did put it on my TODO for this project but haven't gotten around to it yet, thanks for reminding me about it. I'll bump it up the priority list 😄

**Comment by no-stack-dub-sack** [comment]
Thanks! And sorry about the comment coming from a weird account, I was unknowingly signed in with a dummy account.
