### ISSUE TITLE
Odd format when variable is too big for mapping static attribute

### ISSUE THREAD

**Issue by Rogeriohsjr** [dangmai/prettier-plugin-apex#57]
I am not sure but something from this:

    @TestVisible
    public static Map<string, decimal> fmaIntegerParameterNameDefaultValue = new Map<string, decimal>
    {'Parameter1'=> 1,
    'Parameter2' => 0 ,
    'Parameter3'=> 500 };

I got this:

    @TestVisible
    public static Map<string, decimal> fmaIntegerParameterNameDefaultValue = new Map<
        string,
        decimal
        >{
        'Parameter1' => 1,
        'Parameter2' => 0,
        'Parameter3' => 500
    };

I guess is the name of the variable that is big, because if I changed it to test, I got this code below, which looks way better.

    @TestVisible
    public static Map<string, decimal> test = new Map<string, decimal>{
        'Parameter1' => 1,
        'Parameter2' => 0,
        'Parameter3' => 500
    };

My prettier is:
{
  "printWidth": 100,
  "tabWidth": 4,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "trailingComma": "none",
  "bracketSpacing": true,
  "arrowParens": "avoid",
  "rangeStart": 0
}

**Comment by dangmai** [comment]
Thank you for the bug report @Rogeriohsjr 
That output does look weird, I'll include your code sample in the test suite and figure out how to format that better. 
The way Prettier works is that it tries to output as much code in one line as possible (in your case, a line can hold at most 100 characters), and if it can't it will break up the lines. Apparently in this case, the line break I chose did not look very nice :)

**Comment by dangmai** [comment]
I've fixed this in `master`, it will be included in the next release, which I'm aiming to release within a week. Thanks again for the bug report!

**Comment by dangmai** [comment]
FYI I just released a new version that contains the fix for this.
