### ISSUE TITLE
Odd format for SOQL + Comment + SubQuery

### ISSUE THREAD

**Issue by Rogeriohsjr** [dangmai/prettier-plugin-apex#58]
From this code below:

        List<sfLma__License__c> listParentLicenses = [
        SELECT
            Id, 
            Name,
            // Sub-Query - ChildLicense -- Getting All the Child Licenses linked with this Parent
            (SELECT Id, ChildLicenseLookup__c from ChildLicenses__r) 
        FROM sfLma__License__c

I am getting this:

        List<sfLma__License__c> listParentLicenses = [
            SELECT
                Id,
                Name
                    , // Sub-Query - ChildLicense -- Getting All the Child Licenses linked with this Parent
                (SELECT Id, ChildLicenseLookup__c FROM ChildLicenses__r)
            FROM sfLma__License__c

I am not sure how it should looks like, but that ,(comma) there before comment doesn't look right.

**Comment by dangmai** [comment]
Comment in general is really difficult to get right, because they can appear almost anywhere in the code while being syntactically correct. I agree that the output here looks odd, I'll see what I can do for this particular case.

**Comment by dangmai** [comment]
I have fixed this in `master`, it will be available in the next release. I'm hoping that will happen within next week.

Thanks again for the bug report!
