### ISSUE TITLE
Check to see if nested SOQL/SOSL Where Compound Expression can be flattened safely

### ISSUE THREAD

**Issue by dangmai** [dangmai/prettier-plugin-apex#61]
Pinging @praksb, @ntotten
This is a discussion that I'd like to have about SOQL/SOSL in general, and I'm not sure where I can find a definite answer.

Consider this SOQL query:
```
Account[] accounts = [
      select id
      from Account
      where
      (
        Name = 'Test Account'
        AND
        Name = 'Test Account 2'
      )
      AND Status = 'Active'
    ];
```
Right now `jorje` parses the Where Clause as nested `WhereCompoundExpr`, each with its own `QueryAnd` operator.

What I'd like to do is to format this code as:

```
Account[] accounts = [
      select id
      from Account
      where
      Name = 'Test Account'
      AND Name = 'Test Account 2'
      AND Status = 'Active'
    ];
```
Which means that I'll be flattening the structure, making the final AST contain only 1 WhereCompoundExpr with 3 expressions in it.

What I am curious about is whether this is a safe operation, i.e. whether these 2 queries are actually identical or not (for example, can there be a difference in the result from these 2 queries, and/or if there are optimizations that might go into one query but not the other). If there is any kind of difference I will make sure that the flattening does not happen.

The algorithm that I am using to do this is very simple: if a `WhereCompoundExpr` has a parent that is also `WhereCompoundExpr` with the same `op`, then I print them without parentheses, effectively flattening the AST structure.

**Comment by praksb** [comment]
@dangmai I think this should be ok. I am curious  to knowhow you would handle the verify-ast functionality in this case though since the ASTs would be different.

**Comment by dangmai** [comment]
That's great news, I'll move forward with that :) Here's the commit that I put in the AST massaging mechanism: https://github.com/dangmai/prettier-plugin-apex/commit/94e3cae26a03a175aa0ca1456df4192b4de63f61#diff-34a6d62af0cf0b784f8444529f3130ef

The idea is similar to the `dottedExpr` vs `names` mechanism: whenever I look at a `WhereCompoundExpr` node, and it contains other `WhereCompoundExpr` with the same operator type, then I lift those expressions one level up. The process starts from the leaf nodes of the AST and go up the tree so I should be able to handle all nested levels of the expression.
