### ISSUE TITLE
Unexpected formatting for long string concatenated line.

### ISSUE THREAD

**Issue by brsanthu** [dangmai/prettier-plugin-apex#649]
```sh
# Prettier options (if any):
{
  "trailingComma": "es5",
  "singleQuote": true,
  "printWidth": 120,
  "tabWidth": 2,
  "semi": true,
  "bracketSpacing": false,
  "overrides": [
    {
      "files": "**/lwc/**/*.html",
      "options": { "parser": "lwc" }
    },
    {
      "files": "*.{cmp,page,component}",
      "options": { "parser": "html" }
    }
  ]
}


```

**Input:**

```apex
String reqInfo = '[method=' + httpMethod + ', uri=' + restReq.requestURI + ', path=' + restReq.resourcePath + ', handler=' + Utils.getClassName(this) +']';
```

**Actual output:**

```apex
    String reqInfo =
      '[method=' +
      httpMethod +
      ', uri=' +
      restReq.requestURI +
      ', path=' +
      restReq.resourcePath +
      ', handler=' +
      Utils.getClassName(this) +
      ']';
```

**Expected output:**

Expected that string concatenation respects the line length setting and puts them in same line till length has been exhausted. Current output is very verbose and hard to read in my opinion.

Note that if original line is with in the maxLine config, then it is putting all info in single line. 

```apex
    String reqInfo = '[method=' + httpMethod + ', uri=' + restReq.requestURI + ', path=' + restReq.resourcePath 
      + ', handler=' + Utils.getClassName(this) +']';
```

**Additional information (please fill this out)**:

- OS: Mac M1
- Version: 12.3.1

**Comment by dangmai** [comment]
Hi, thank you for opening the issue.

While I understand where you're coming from with this request, I don't foresee myself making this change. This is an opinionated library, and the current behavior allows us to align with how Prettier core formats other languages. For example, this is how Prettier formats very similar code [in Javascript](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAnOBHAklAZhAAgF4CByAbQFs4YALCAEyNIIGoDaYYAHAWRvoM2ZADQEArqgCWzYegDOMAEqYAdOgzi4igKpKsw0mO4BDOrPYLlahRElg4ABTO1DY2iagMANnFQWCHRgpb3lVAHMaAGFvE3l5ADkTagAKOil5AEo2UgBdUgBuEBEQCG5g6HlkUBNUVAgAd2d0KCqUE28GkwBPKpKAI1QTMABrGgBlZLgAGSkoOGRcDvk4AaHRidMwOfDkGFQtErhKfrgGBjPpz3DxE0iAMQhUSjNgqF328RgIYpBOSm8AHVaFJ4PItnBxgh5KCpAA3UHdZDgeK-OYrVAwRxDcIvRbLVYgABW8gAHuMdr4AIriCDwfGhQmmVAY5H9Eynby-bjSWCAqQMOjIAAcAAYSjyICtAUNuMiedo-HCFiVNHSnPVuG0QHEALTzM5nX4acRSdDYu54pBLRklFaUKR7A6EmHvam0+nWgklGAc-mC2jIABMPqGIR2UQglCtIG0AFZfuIVgAVDltG0rEpwrQ4C6wcZgaTlACCXnGMG6vgZKwAvjWgA). If we changed the behavior here, it'll be really confusing for the users that uses Prettier for both Apex and JS (which I'm sure a lot of users are).

**Comment by brsanthu** [comment]
While I don't agree with how prettier or prettier-apex formats for this use-case, I'd understand and agree with your reasoning. Thank you.
