### ISSUE TITLE
Migrate to Prettier v3

### ISSUE THREAD

**Issue by sosukesuzuki** [dangmai/prettier-plugin-apex#673]
Sorry for ignoring the issue template..

Hi, I am a maintainer at Prettier.

The Prettier team is currently working on v3(still alpha).
v3 will include breaking changes to the plugin interface.
Please see https://github.com/prettier/prettier/releases/tag/3.0.0-alpha.2 for more information.

I created this issue to help major plugins migrate to Prettier v3.

Myself and @fisker have created a migration guide which you can see here:

https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F

If you have any questions, feel free to mention us. We can help you.

If you have already migrated to Prettier v3, sorry but please close this issue.

**Comment by dangmai** [comment]
Hey @sosukesuzuki, I'm working on supporting Prettier v3 in my plugin, and I'll reach out if I have any question.

Currently, the only question I have is about timeline - I'd like to support v3 as soon as it's out, but not sure if I have enough time in the short term to finish the migration. Does upstream know roughly when the first v3 will be published?

**Comment by fisker** [comment]
We still have some tasks not finished, may need take a while. https://github.com/prettier/prettier/issues/13142

**Comment by dangmai** [comment]
> We still have some tasks not finished, may need take a while. [prettier/prettier#13142](https://github.com/prettier/prettier/issues/13142)

Great, thank you for the info!

**Comment by dangmai** [comment]
Forgot to update this ticket - I have been working on Prettier v3 support in `prettier-v3` branch. It is working fine with a big speed boost. I have now merged that branch into `main`, so that going forward it'll be the default.

`1.13.0` will be the last version to support Prettier v2, unless there's a critical issue that requires backporting.

**Comment by dangmai** [comment]
Released version `2.0.0` that supports Prettier v3. Closing this ticket.
