### ISSUE TITLE
No handler found for apex.jorje.data.soql.Geolocation$GeolocationExpr

### ISSUE THREAD

**Issue by jwoodwardffdc** [dangmai/prettier-plugin-apex#674]
```sh
# Prettier options (if any): none?
```

**Input:**
```apex
		List<Contact> peeps = [
			SELECT
				Id,
				Name,
				Distance(MailingAddress, :resourceRequestGeoLocation, 'km')
			FROM Contact
			WHERE Id IN :someIds
			ORDER BY Distance(MailingAddress, :resourceRequestGeoLocation, 'km')
		];
```

**Actual output:**

It has an error
*** cmd start: node_modules/.bin/prettier --write /Users/jwoodward/git/psa/appirio-core/force-app/main/configManagement/classes/CM_ExportConfigurationController.cls --config .prettierrc

[error] force-app/main/configManagement/classes/CM_ExportConfigurationController.cls: Error: No handler found for apex.jorje.data.soql.Geolocation$GeolocationExpr. Please file a bug report.
[error]     at genericPrint (/Users/jwoodward/git/psa/appirio-core/node_modules/prettier-plugin-apex/src/printer.js:2873:9)
[error]     at Object.printGenerically [as print] (/Users/jwoodward/git/psa/appirio-core/node_modules/prettier-plugin-apex/src/printer.js:2884:15)
[error]     at callPluginPrintFunction (/Users/jwoodward/git/psa/appirio-core/node_modules/prettier/bin-prettier.js:14572:18)
[error]     at /Users/jwoodward/git/psa/appirio-core/node_modules/prettier/bin-prettier.js:14522:47
[error]     at Object.printComments (/Users/jwoodward/git/psa/appirio-core/node_modules/prettier/bin-prettier.js:14195:19)
[error]     at printGenerically (/Users/jwoodward/git/psa/appirio-core/node_modules/prettier/bin-prettier.js:14522:22)
[error]     at FastPath.call (/Users/jwoodward/git/psa/appirio-core/node_modules/prettier/bin-prettier.js:14315:20)
[error]     at Object.handleDistanceFunctionExpression [as apex.jorje.data.soql.DistanceFunctionExpr] (/Users/jwoodward/git/psa/appirio-core/node_modules/prettier-plugin-apex/src/printer.js:1962:26)
[error]     at genericPrint (/Users/jwoodward/git/psa/appirio-core/node_modules/prettier-plugin-apex/src/printer.js:2863:34)
[error]     at Object.printGenerically [as print] (/Users/jwoodward/git/psa/appirio-core/node_modules/prettier-plugin-apex/src/printer.js:2884:15)
Run on Save done.

**Expected output:**

No error!

**Additional information (please fill this out)**:

- OS: MacOS Monterey
- Version: Reproduced on 1.8.0 and 1.10.0
- Java openjdk version "11.0.16.1"

**Comment by dangmai** [comment]
Hi, thank you for opening this issue. You're correct that this is a bug - I haven't come across this node type being used before so it's not yet implemented in this library. I'll add support for it soon.
