### ISSUE TITLE
Long static method calls produce semantically incorrect code

### ISSUE THREAD

**Issue by SteffenPegenau** [dangmai/prettier-plugin-apex#69]
```sh
--write
```

**Input:**
```apex
public static Map<String, Schema.RecordTypeInfo> accRTs = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
```

**Output:**
```apex
public static Map<String, Schema.RecordTypeInfo> accRTs = Schema
        .SObjectType
        .Account
        .getRecordTypeInfosByDeveloperName();
```

**Expected behavior:**
Not cutting .SObjectType off

**Additional information (please fill this out)**:
As the output looks pretty clean, sfdx could not compile it: "Variable does not exist: Schema"

I was able to fix it by
* manually removing the line ending after Schema
* increasing the printWidth config value (i.e. to 160)

- OS: Windows
- Version: 1.0.0-beta.1

**Comment by dangmai** [comment]
Hey @SteffenPegenau, thanks for the bug report! Do you still run into this issue? Sometimes Salesforce parser is really finicky when it comes to white spaces, so I want to make sure that `prettier-plugin-apex` does not format in a way that cannot be deployed.

**Comment by dangmai** [comment]
I actually just tried this in my sandbox and you're right - this is indeed a bug. I'll reopen this and make sure it gets fixed asap.

**Comment by dangmai** [comment]
I've published a new version that should fix this issue. Please update and let me know if you run into any further problem. The quality/correctness of the output is very important to me so I'll do my best to address them if they come up.

Thank you again for the bug report!
