### ISSUE TITLE
Odd wrapping of logical expressions in sobject constructors

### ISSUE THREAD

**Issue by no-stack-dub-sack** [dangmai/prettier-plugin-apex#693]
Hey @dangmai - this was a little unexpected as the expression is less than the print width of 100 I have set. If you extract the expression into a variable it does not get wrapped, e.g. 

```apex 
Boolean isActive = foo.Active__c == true || foo.Status__c == 'Active';
```

My issue with the actual output is that at a quick glance, its really easy to mistake these as two separate lines that are each arguments of the constructor.

Let me know what you think or if this is expected.

**Input:**

```apex
private static FooWrapper wrapFoo(Foo__c foo) {
  return new UsernameWrapper(foo.Id, foo.Name, foo.Account__c, foo.Active__c == true || foo.Status__c == 'Active');
}
```

**Actual output:**

```apex
  private static FooWrapper wrapFoo(Foo__c foo) {
    return new UsernameWrapper(
      foo.Id,
      foo.Name,
      foo.Account__c,
      foo.Active__c == true &&
      foo.Status__c == 'Active'
    );
  }
```

**Expected output:**

```apex
private static FooWrapper wrapFoo(Foo__c foo) {
  return new UsernameWrapper(
    foo.Id,
    foo.Name,
    foo.Account__c,
    foo.Active__c == true && foo.Status__c == 'Active'
  );
}
```

**Additional information (please fill this out)**:

- OS: Windows 10
- Plugin Version: 1.11.0

**Comment by dangmai** [comment]
Thanks for the bug report. I do agree that the current output is not ideal. I'm looking at it right now and the reason it's that way is because of some other complex binary expression formatting decision made a while ago. If I can make this change without affecting that decision, I'll fix it. It seems to be pretty complex though.

**Comment by dangmai** [comment]
This has been fixed in `master` and will be included in the next release.
