### ISSUE TITLE
Breaking change from 1.10.0 to 1.11.0: local parser start/stop commands path

### ISSUE THREAD

**Issue by pozil** [dangmai/prettier-plugin-apex#698]
Hi @dangmai. Thanks again for the great work that you put up with the plugin.
I just want to raise the fact that you introduced a breaking change with v1.11.0:

When using the library within a project (not a global install), the command to start/stop the local Apex parser moved from
```
node_modules/prettier-plugin-apex/bin/start-apex-server.js
```
to
```
node_modules/prettier-plugin-apex/dist/bin/start-apex-server.js
```

Note the extra `dist` in the path.
It's not  a big deal but you may want to document it in the release notes.

**Comment by dangmai** [comment]
Hello, thank you for pointing this out. This is an oversight on my part, I changed the README to mention this change, but forgot to include that in the CHANGELOG. This has been now been added to both `CHANGELOG.md` and the Release log.
