### ISSUE TITLE
Feature Request: visualforceInsertFinalNewline option

### ISSUE THREAD

**Issue by dschach** [dangmai/prettier-plugin-apex#716]
With Prettier forcing a final new line for Visualforce (and then the Salesforce platform deleting it) PRs are full of unnecessary changes.

It's great to put the apexInsertFinalNewLine option in here; can we do the same for Visualforce (pages and components)?

**Comment by dangmai** [comment]
Hi, this library only formats Apex codes, not Visualforce or Aura/LWC, so that's not something I can do. Most likely you're formatting VF with the HTML plugin, which is part of upstream Prettier. You can request that feature from them, but most likely they'll say no unfortunately.
