### ISSUE TITLE
No longer preventing adding a new line at end of Apex class

### ISSUE THREAD

**Issue by dschach** [dangmai/prettier-plugin-apex#720]
With the new release, setting `apexInsertFinalNewline` to `false` has no effect on Prettier - it still adds an extra line at the end of my Apex classes.

This is for every class I format on save, though I have noticed that Prettier doesn't flag any classes when doing a verify... so I'm extra-confused!

**Comment by dangmai** [comment]
Hi, can you post your Prettier config here please? Does this only happen to the newest release, or have you tried with an old release?

Thanks!

**Comment by dangmai** [comment]
I just tried it on my end with latest Prettier and Prettier Apex and the flag works fine on my machine, so I'm leaning towards something being misconfigured on your end.

**Comment by dschach** [comment]
It only started doing it this week (but I was not coding the past two weeks either). I just installed 1.11.0 and it is still doing it, so I am worried that it is something on my end. 

```
{
	"trailingComma": "none",
	"singleQuote": true,
	"tabWidth": 2,
	"printWidth": 150,
	"useTabs": true,
	"bracketSpacing": true,
	"apexInsertFinalNewline": false,
	"bracketSameLine": true,
	"endOfLine": "lf",
	"overrides": [
		{
			"files": "**/lwc/**/*.html",
			"options": { "parser": "lwc", "useTabs": true, "printWidth": 150 }
		},
		{
			"files": "*.{cmp,page,component}",
			"options": { "parser": "html" }
		},
		{
			"files": "**/*meta.xml",
			"options": { "parser": "xml", "useTabs": false }
		},
		{
			"files": "**/*.yml",
			"options": { "parser": "yaml", "singleQuote": true }
		},
		{
			"files": "**/workflows/*.yml",
			"options": { "parser": "yaml", "singleQuote": true }
		},
		{
			"files": "*.trigger",
			"options": { "parser": "apex", "singleQuote": true, "printWidth": 180 }
		}
	]
}
```

**Comment by dschach** [comment]
Update: It magically works now. Sorry for the inconvenience. I installed 1.11.0 and then 1.12.0 and something went right.

**Comment by dangmai** [comment]
I'm glad you got it working!
