### ISSUE TITLE
Parse error on "as user" keywords (User Mode for Database Operations)

### ISSUE THREAD

**Issue by pozil** [dangmai/prettier-plugin-apex#738]
Hi @dangmai, I guess that this issue will be closed with the Jorje update that you're working on but I felt that I should report it anyways for visibility.

Over the last couple of release we've introduced [User Mode for Database Operations](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_enforce_usermode.htm). This adds new `as user` Apex keywords.

The current version of the parser embedded in the Apex Prettier plugin is failing to parse the following valid Apex code:
```apex
insert as user newContact;
```

This produces an error like this:
```
Error:  Unexpected token 'as'..
Error:      at Object.parse (/home/runner/work/visualforce-to-lwc/visualforce-to-lwc/node_modules/prettier-plugin-apex/dist/src/parser.js:467:19)
Error:      at Object.parse (/home/runner/work/visualforce-to-lwc/visualforce-to-lwc/node_modules/prettier/index.js:7331:23)
Error:      at coreFormat (/home/runner/work/visualforce-to-lwc/visualforce-to-lwc/node_modules/prettier/index.js:8645:18)
Error:      at formatWithCursor2 (/home/runner/work/visualforce-to-lwc/visualforce-to-lwc/node_modules/prettier/index.js:8837:18)
Error:      at Object.formatWithCursor (/home/runner/work/visualforce-to-lwc/visualforce-to-lwc/node_modules/prettier/index.js:37832:12)
Error:      at format (/home/runner/work/visualforce-to-lwc/visualforce-to-lwc/node_modules/prettier/cli.js:[14](https://github.com/trailheadapps/visualforce-to-lwc/actions/runs/3795057895/jobs/6453778921#step:6:15)789:24)
Error:      at formatFiles2 (/home/runner/work/visualforce-to-lwc/visualforce-to-lwc/node_modules/prettier/cli.js:14903:22)
Error:      at async main (/home/runner/work/visualforce-to-lwc/visualforce-to-lwc/node_modules/prettier/cli.js:[15](https://github.com/trailheadapps/visualforce-to-lwc/actions/runs/3795057895/jobs/6453778921#step:6:16)128:5)
Error:      at async Object.run (/home/runner/work/visualforce-to-lwc/visualforce-to-lwc/node_modules/prettier/cli.js:15075:5)
Error:  force-app/main/default/classes/CreateMixedRecordsApexControllerLwc.cls: Error: Unexpected token 'as'..
```

Thanks again for all of the hard work you're putting on the plugin.

**Comment by dangmai** [comment]
Thank you for opening this issue. I've been checking to see if `jorje` supports this new syntax for a while, but haven't seen any update with regards to it. It looks like the LSP does support this syntax now though, I'll check to see how it's being done in the LSP.

**Comment by dangmai** [comment]
The error is coming straight from `jorje`, so my hunch is that there might be some flag I need to pass in so that this syntax can be parsed. Do you have any contact in the team that owns `jorje` or LSP that I can talk to in order to understand how to implement this properly?

FYI this is how Apex code is being parsed by `apex-ast-serializer`: https://github.com/dangmai/apex-ast-serializer/blob/master/src/main/java/net/dangmai/serializer/Apex.java#L49

Thanks!

**Comment by pozil** [comment]
Thanks for investigating. I'll try to find the right people and send them your way.

**Comment by drd0013** [comment]
+1 to this issue

**Comment by pozil** [comment]
Hi @dangmai, it took a bit of time to chase the right owner for this and I had to send a friendly reminder but this is now tracked and the team should update the JAR soon. I'll keep you posted if I hear anything.

**Comment by dangmai** [comment]
Thank you so much for tracking that down @pozil! I will add support for this syntax and release a new version as soon as the new JAR is out 👍

**Comment by nabondance** [comment]
Hello, we have the same issue with `as system`

**Comment by nwcm** [comment]
Also having this issue

**Comment by pozil** [comment]
Hi all, this is still on the backlog of our tooling team. I'll send them a reminder but it looks like they are swamped with requests.

**Comment by dangmai** [comment]
Support for `as user` and `as system` keywords in DML operations has been added and released in Prettier Apex 1.13.0.

**Comment by pozil** [comment]
Thanks @dangmai. I'm surprised that I didn't get the update that jorge had been updated but I'm glad that you saw it first :)

**Comment by AnanyaJha** [comment]
Thank you for the quick update @dangmai ! To answer your question Philippe, we haven't **released** the new version of the Apex Extension with the updated LSP jar yet, but it's been merged in. Should be going out this week and we'll update you all officially then :)

**Comment by tehnrd** [comment]
Very important tip. After updating, make sure to shut down and restart VS Code completely. I didn't do this at only did `npm i` then formatted code and it changed `upsert as user setting;` to `upsert setting;` Restart fixed this and it isn't removing the `as user` part any more.
