### ISSUE TITLE
Prettier formatting single line if statements

### ISSUE THREAD

**Issue by agentgruer** [dangmai/prettier-plugin-apex#74]
I have single line if statements in my code base and when running Prettier, it breaks up the if statements into multiple lines without adding curly brackets. Is it possible to either have a setting to ignore the single line if statements or add curly brackets if it breaks up a single line if statement into 2+ lines? This does cause PMD to throw an issue as you shouldn't have if statements without curly brackets, and this prettifying could lead to issues with developers believing they are adding logic to the if statement due to the indentation giving that impression.

**Input:**
```apex
if(hasCondition) return null;
```

**Output:**
```apex
if(hasCondition)
  return null;
```

**Expected behavior:**
```apex
if(hasCondition){
  return null;
}
```

**Additional information (please fill this out)**:
- OS: OS X
- Version: 1.0.0-rc.2

**Comment by dangmai** [comment]
Hi, thank you for the report, I appreciate it!

This has been requested before; however I'm following Prettier's philosophy here that it is [not a code transformer](https://prettier.io/docs/en/rationale.html#what-prettier-is-not-concerned-about). This issue falls into that category, so it's out of scope for this project.

I believe PMD is the right tool for the job here and it's doing the right thing - which is to warn the developers about a potential code smell. 

If you really want to keep the original formatting, feel free to add a `// prettier-ignore` line before it and that line of code will be ignored.

**Comment by agentgruer** [comment]
Thanks for the response, and that makes sense. Thanks for the great tool!
