### ISSUE TITLE
Debug check fails for illegal code

### ISSUE THREAD

**Issue by praksb** [dangmai/prettier-plugin-apex#78]
The following code fails Apex prettier --debug-check:

Integer i;

Debug check fails with the following error:
AnonymousClass.cls[error] AnonymousClass.cls: Error: Unexpected token 'Integer'.. Syntax(error = UnexpectedToken(loc = (1, 1, 0, 7), token = 'Integer'))
[error]     at Object.parse (/usr/local/lib/node_modules/prettier-plugin-apex/src/parser.js:452:13)
[error]     at Object.parse$2 [as parse] (/usr/local/lib/node_modules/prettier/bin-prettier.js:10635:19)
[error]     at coreFormat (/usr/local/lib/node_modules/prettier/bin-prettier.js:13844:23)
[error]     at format (/usr/local/lib/node_modules/prettier/bin-prettier.js:14103:73)
[error]     at formatWithCursor (/usr/local/lib/node_modules/prettier/bin-prettier.js:14119:12)
[error]     at /usr/local/lib/node_modules/prettier/bin-prettier.js:42520:15
[error]     at Object.format (/usr/local/lib/node_modules/prettier/bin-prettier.js:42539:12)
[error]     at format$1 (/usr/local/lib/node_modules/prettier/bin-prettier.js:43805:25)
[error]     at /usr/local/lib/node_modules/prettier/bin-prettier.js:44084:16
[error]     at /usr/local/lib/node_modules/prettier/bin-prettier.js:44024:14

**Comment by dangmai** [comment]
Hmm I actually think this is correct behavior - I'm not sure what else we can do rather than failing? We can't parse that file because it's not legal Apex code in Named mode.

It looks like correct code in Anonymous mode though, so if you add the `--apex-anonymous` flag, it should format that without issue.

**Comment by praksb** [comment]
Yes. --apex-anonymous works. closing this.
