### ISSUE TITLE
Error: No handler found for apex.jorje.data.ast.AnnotationParameter$AnnotationString.

### ISSUE THREAD

**Issue by joeferraro** [dangmai/prettier-plugin-apex#80]
**Input:**
```apex
@SuppressWarnings('PMD.ApexCRUDViolation')
public with sharing class SomeClass {

    public class SomeInnerClass {
        @AuraEnabled
        public String someProperty;
    }
```

**Output:**
Error

**Expected behavior:**
Prettifies

- OS: OS X
- Version: v1.0.0-rc.2

**Comment by dangmai** [comment]
Thank you for the bug report. That is indeed a problem - apparently none of the test repositories I use for integration tests have this form of annotation. I'll fix this soon and the fix will be in the next release.

In the mean time you can temporarily disable prettier for that class by including `// prettier-ignore` before it.

**Comment by dangmai** [comment]
I've released `rc4` that contains a fix for this.
