### ISSUE TITLE
Do not insert final newline 

### ISSUE THREAD

**Issue by jairzh** [dangmai/prettier-plugin-apex#83]
To use the `prettier` to format a class, then deploy the code to a sandbox/dev org, retrieve it from the org, you will find the end of newline will be removed by Salesforce. 

That is not friendly for the source control and code review.

**Comment by dangmai** [comment]
Thank you for the issue report! I've tried this in my sandbox and you're right, Salesforce trims the class source codes.

I'm debating whether removing the final new lines would be the right thing to do though - Prettier core forces new lines at the end of a formatted files, and it is used to format Aura and LWC JS files so presumably you will run into this issue on those files as well. I think the right thing to do is to convince Salesforce to preserve those new lines instead :)

@ntotten, @praksb Can you guys chime in here about the possibility of preserving the final newline from Salesforce?

It's not a technically difficult thing to do for this library, but I'm hoping that we can make a decision that is consistent across different languages that Prettier supports on the Salesforce platform.

**Comment by praksb** [comment]
@dangmai This trimming that occurs seems to be specific to Apex only. This happens while saving an Apex class after a successful compilation. It is not clear why we trim the class before we save in the DB. I have logged a bug to see if the team that owns it can fix it. At this point it is not clear if the team would fix it though in the current release. I would suggest that we just fix this in the library for now if possible.

**Comment by dangmai** [comment]
@praksb I just tried it with an Aura and LWC components in multiple formats (`.cmp`, `.css`, `.js`) and they all get trimmed once I retrieve from the sandbox using VSCode. Could you double check that this issue only affects Apex code?

**Comment by praksb** [comment]
@dangmai I see that now for Aura and LWC components and I don't know why we are doing it. I am trying to find out why and will let you know once I have more info.

**Comment by dangmai** [comment]
I actually just ran into this in my company code base while using Prettier for Aura/LWC formatting. Prettier adds a trailing empty line for those files so in the VCS those files have them. However, we also have a nightly job that pulls down the org metadata into the VCS so that it always contains what is in Production, and all those newlines are removed there, creating a lot of unnecessary merge conflicts later on.

@ntotten what are your thoughts on this issue? I can change the behavior for `prettier-plugin-apex` to stop inserting new lines pretty easily, but I know `prettier` core won't make that change and/or add an option for it (see https://github.com/prettier/prettier/issues/2575) for the languages they support out of the box.

**Comment by ntotten** [comment]
Yeah, I don't love that we strip new lines on the backend, but I am also not sure if it is something we can change. My guess is they are doing something like `{code}.trim()` to remove any extra white space that will take up storage in the backend DB.

I think for now we should not change the behavior of prettier, but we should document how to deal with this. I suppose you could update your script that pulls the files and check to make sure they always have a new line appended.

One possible fix is adding an option to the CLI that ensures files have new lines.

**Comment by dangmai** [comment]
Those are good suggestions. I think for `prettier-plugin-apex` I will keep the trailing new line as the default since that's how Prettier core works, but I'll add an option so that it can be removed to make it easier for the users.

**Comment by dangmai** [comment]
I've added an option `--apex-insert-final-newline` that defaults to `true` in the `master` branch. It will be included in the next release, which most likely will be `1.0.0`.

**Comment by dangmai** [comment]
`1.0.0-rc.5` has been published and contains this option.

**Comment by benjaminloerincz** [comment]
I run into the same issue regarding source control. For other files than apex in a Salesforce project I am using this vscode extension in addition to prettier: https://marketplace.visualstudio.com/items?itemName=DoCode.vscode-remove-final-newlines

**Comment by dangmai** [comment]
That's a great suggestion, thank you @benjaminloerincz !
