### ISSUE TITLE
Apex Prettier plugin is too slow to be usable

### ISSUE THREAD

**Issue by AndrewRayCode** [dangmai/prettier-plugin-apex#843]
```sh
npx prettier --version
2.8.7
```

Just a handful of files:
```
ls -al **/*.{trigger,cls} | wc -l
     497
```

But a job that should take seconds takes minutes
```
time npx prettier --check **/*.{trigger,cls}

real	8m7.888s
user	20m31.231s
sys	2m39.376s
```

Compare to JS prettier for a similar amount of JS files:
```
ls -Ral | grep '.js$' | wc -l
     299

time npx prettier --check '**/*.js'

real	0m4.436s
```

Engineering dev tools must be fast. This is both an issue for local development as well as for CI, our CI steps are failing due to timeouts. We could update the CI timeout but this should still be a very fast task.

There appears to be something fundamentally wrong with our use of prettier, like an O(log n) vs an O(n) difference. Can you help me understand the source of the slowness? Do we need to configure something differently?

**Comment by dangmai** [comment]
This has been addressed multiple times:
- On the README: https://github.com/dangmai/prettier-plugin-apex#performance-tips3rd-party-integration
- In this issue: https://github.com/dangmai/prettier-plugin-apex/issues/287
- As well as this issue: https://github.com/dangmai/prettier-plugin-apex/issues/118

There will be a big performance boost when prettier v3 (the upstream project, not this library), but until then there's very little I can do.

**Comment by AndrewRayCode** [comment]
Thanks, using the server got us down to 5 minutes! Not great but acceptable for CI.

Even with the overhead of spawning shell processes and java startup I'm surprised how slow parsing is given that it's Java. It might be a fun project to write a parser for Apex it in peggyjs. One of the benefits of Apex being a stale little immature language is that it doesn't have a big surface area. I'll try it out if I have a bored free weekend or three!
