### ISSUE TITLE
Decimal reformating causes functional change

### ISSUE THREAD

**Issue by nawforce** [dangmai/prettier-plugin-apex#88]
**Input:**
```apex
Map<String, Decimal> a = new Map<String, Decimal>{'k' => 0.1230};
Map<String, Decimal> b = new Map<String, Decimal>{'k' => 0.1230};
Map<String, Decimal> c = new Map<String, Decimal>{'k' => 0.123};

System.debug(a==b);	// true
System.debug(a==c);	// false
```

**Output:**
```apex
Map<String, Decimal> a = new Map<String, Decimal>{'k' => 0.123};
Map<String, Decimal> b = new Map<String, Decimal>{'k' => 0.123};
Map<String, Decimal> c = new Map<String, Decimal>{'k' => 0.123};

System.debug(a == b); // true
System.debug(a == c); // true
```

**Expected behavior:**
Trailing zeros on Decimals are not removed. This is pretty horrible platform behavour but we have some tests that have been coded in a way that they have become sensitive to this when checking rounding handling so these break after reformating.

**Additional information (please fill this out)**:

- OS: OS X
- Version: 1.0.0-rc.5

**Comment by dangmai** [comment]
Oh wow that's a serious bug, thank you for the report! I definitely did not expect those to be different at all. By this point I can write a book about quirky Apex behaviors that I've found during my development of this library 😄 I'll make a fix for it soon. In the mean time you can put a `// prettier-ignore` comment before that line so that it doesn't get formatted by Prettier.

**Comment by dangmai** [comment]
I have fixed this in `master` and will include it in the next release.

**Comment by nawforce** [comment]
Thanks for quick fix. What I should have mentioned is how impressed I am with the formatting, that was the only issue I found in a ~300 KLOC package which is very good going indeed.

**Comment by dangmai** [comment]
Thank you! I have an integration test set up that runs this library over most of the popular Apex packages (see [here](https://github.com/dangmai/prettier-plugin-apex/blob/master/tests_integration/test-repos.txt)), and it's also been run on my company internal code base (~ 8 million Apex characters) and some Salesforce internal code bases (I can't imagine how big those are), so hopefully at this point most of the bugs have been found. If you are aware of another public Apex repo I'll be glad to add them to my integration test suite.
