### ISSUE TITLE
Questions about potential enhancements

### ISSUE THREAD

**Issue by kyle-blair** [dangmai/prettier-plugin-apex#968]
Hi @dangmai, I'd like to contribute some enhancements but I have a few questions. Before I start, do you have a responsible disclosure policy for vulnerabilities?

I'm also curious if the http server under [vendor/apex-ast-serializer](https://github.com/dangmai/prettier-plugin-apex/tree/master/vendor/apex-ast-serializer) is used even when locally running simple formatting commands? If so, I'm curious if there are other ways to manage those jar dependencies under the `lib` directory that you may have ruled out for good reason. I'd like to bump some of those jar dependency versions if possible.

**Comment by dangmai** [comment]
Hello, thank you for opening the ticket!

We don't have a formal disclosure policy for vulnerabilities. If you have a critical vulnerability you'd like to report, please shoot me an email at contact (at) dangmai.net

To answer your other questions, by default the HTTP Server won't be used. They are only used if the user specifies the `apexStandaloneParser` parameter.

I'm curious which jar you'd like to update? The vendor jars come from the https://github.com/dangmai/apex-ast-serializer project, and it has Renovate set up on it so it most likely contains the most updated version of all dependencies already. Without bundling the vendor jars as part of Prettier Apex, it's pretty difficult to know for sure that they all work together. Do you have suggestions on how that could be handled better?

**Comment by kyle-blair** [comment]
That separate project is what I was looking for; a place to build via gradle or maven. Is the output from that project manually translated into this one? Particularly with respect to the jar files under `vendor/apex-ast-serializer/lib`. I'll shoot you a quick email.

**Comment by dangmai** [comment]
This has been resolved as of `v2.1.0`
