### ISSUE TITLE
Formatting issues for variable assignment

### ISSUE THREAD

**Issue by kend77** [dangmai/prettier-plugin-apex#98]
**Input:**

```apex
this.account_executive = new UserResource(desk.getAccountExec());
this.hours_of_operation = desk.acct.Hours_of_Operation__c;
this.public_name = desk.acct.CCx_Program_Name_Public__c;
this.rdb_subscription = desk.getRdbSubscription();
this.default_clinical_communication = desk.getClinicalCommDeliveryMethod();
```

**Actual output:**

```apex
this.account_executive = new UserResource(desk.getAccountExec());
this.hours_of_operation = desk.acct.Hours_of_Operation__c;
this.public_name = desk.acct.CCx_Program_Name_Public__c;
this.rdb_subscription = desk.getRdbSubscription();
this
     .default_clinical_communication = desk.getClinicalCommDeliveryMethod();
```

**Expected output:**

```apex
this.account_executive = new UserResource(desk.getAccountExec());
this.hours_of_operation = desk.acct.Hours_of_Operation__c;
this.public_name = desk.acct.CCx_Program_Name_Public__c;
this.rdb_subscription = desk.getRdbSubscription();
this.default_clinical_communication =
     desk.getClinicalCommDeliveryMethod();
```

**Additional information (please fill this out)**:

- OS: OS X
- Version: 1.0.0-beta.2

**Comment by dangmai** [comment]
Thank you for the bug report, I agree with the expected output. I think the sane thing to do is to make sure the left hand side of a variable expression should never be broken up

**Comment by jdcrensh** [comment]
Similarly, we have this (printWidth=40):

**Input:**
```
  public List<Account> method() {
    return this.someMethod(a, b, c, d, e, f, g);
  }
```

**Actual Output:**
```
  public List<Account> method() {
    return this
      .someMethod(a, b, c, d, e, f, g);
  }
```

**Expected Output:**
```
  public List<Account> method() {
    return this.someMethod(
      a,
      b,
      c,
      d,
      e,
      f,
      g
    );
  }
```

**Comment by dangmai** [comment]
Hey @jdcrensh, thanks for the report!

I think that is a different discussion from the issue that OP reported (his is specifically about breaking up the left hand side of an assignment expression). For your example, I actually think the current output is preferable because IMO it is no less readable than the expected output, but with the pros of saving characters that are limited commodity in the Apex world (my company's org surpasses the 6MB limit for Apex code long ago - and white spaces do count).

I can be convinced otherwise though :) I know Prettier core formats like your expected output, but they don't have to deal with the artificial limit of characters.

**Comment by jdcrensh** [comment]
Sorry, my example was actually supposed to highlight the problem with `this.someMethod` turning into `this<break>.someMethod`. The parameter list is just there to illustrate the behavior.

**Comment by dangmai** [comment]
Ah I see! In your opinion then should we never break after `this`?. How about this code:

```
return this.methodOne().methodTwo().methodThree();
```

Currently it is formatted as:

```
return this
  .methodOne()
  .methodTwo()
  .methodThree();
```
Would you prefer it to be:

```
return this.methodOne()
  .methodTwo()
  .methodThree();
```

**Comment by jdcrensh** [comment]
In the case of a chain, I'd expect the current functionality as-is. For single method, however, i'd expect it to never break. This would match how prettier works on JS.

**Comment by dangmai** [comment]
I have fixed the the issue in the original post by @kend77.

@jdcrensh I will create another ticket to track your suggestion.
